
var SCIIP_V8_PROPERTY_EXPLORER=(function(){
  function clone_(v){return JSON.parse(JSON.stringify(v));}
  function properties_(){return [
    {propertyId:"PROP-RIALTO-2125-LOWELL",address:"2125 W Lowell St",city:"Rialto",availableSf:664859,clearHeightFt:42,dockHighDoors:82,trailerParking:398,truckCourtFt:185,powerAmps:8000,status:"PLANNED",ownership:"Brookfield",watchlisted:true},
    {propertyId:"PROP-RIALTO-SLOVER-18012",address:"18012 Slover Ave",city:"Rialto",availableSf:310000,clearHeightFt:36,dockHighDoors:42,trailerParking:68,truckCourtFt:185,powerAmps:3000,status:"SUBLEASE",ownership:"Institutional",watchlisted:false},
    {propertyId:"PROP-PERRIS-20123-HARVILL",address:"20123 Harvill Ave",city:"Perris",availableSf:225000,clearHeightFt:36,dockHighDoors:28,trailerParking:54,truckCourtFt:185,powerAmps:2000,status:"PENDING_COMPARABLE",ownership:"Private",watchlisted:false}
  ];}
  function createState(){var p=properties_();return {version:"v8.0-sprint5.0",workspace:"property-explorer",applicationStatus:"OPERATIONAL",properties:p,selectedPropertyId:p[0].propertyId,filters:{city:"ALL",status:"ALL",watchlistedOnly:false},savedViews:[{id:"VIEW-ALL",name:"All Properties"},{id:"VIEW-WATCHLIST",name:"My Watchlist"}],map:{synchronized:true,selectedMarkerId:p[0].propertyId,visibleMarkerCount:p.length},liveRefresh:{status:"CONNECTED",revision:4}};}
  function filter(state,filters){state=clone_(state);state.filters=Object.assign({},state.filters,filters||{});var rows=state.properties.filter(function(p){return (state.filters.city==="ALL"||p.city===state.filters.city)&&(state.filters.status==="ALL"||p.status===state.filters.status)&&(!state.filters.watchlistedOnly||p.watchlisted);});state.map.visibleMarkerCount=rows.length;return {state:state,rows:rows};}
  function select(state,id){state=clone_(state);var p=state.properties.filter(function(x){return x.propertyId===id;})[0];if(!p)throw new Error("Unknown property");state.selectedPropertyId=id;state.map.selectedMarkerId=id;return {state:state,property:p,relationships:{nodes:3,edges:2,status:"SYNCHRONIZED"},timeline:{events:3,permanentHistory:true},documents:{linked:2},detail:{powerAmps:p.powerAmps,availableSf:p.availableSf}};}
  function toggleWatchlist(state,id){state=clone_(state);state.properties.forEach(function(p){if(p.propertyId===id)p.watchlisted=!p.watchlisted;});return state;}
  function saveView(state,name,filters){state=clone_(state);state.savedViews.push({id:"VIEW-"+(state.savedViews.length+1),name:name,filters:filters||{}});return state;}
  function quickAction(id,action){var allowed=["OPEN_GIS","COMPARE","CREATE_WATCHLIST","BEGIN_ANALYSIS"];if(allowed.indexOf(action)<0)throw new Error("Unsupported action");return {propertyId:id,action:action,status:"AVAILABLE",destructive:false,approvalRequired:action==="BEGIN_ANALYSIS"};}
  function certify(){var failures=[],s=createState(),f=filter(s,{city:"Rialto"}),x=select(s,s.selectedPropertyId),w=toggleWatchlist(s,"PROP-PERRIS-20123-HARVILL"),v=saveView(s,"Large Rialto",{city:"Rialto"}),a=quickAction(s.selectedPropertyId,"OPEN_GIS");function t(n,c){if(!c)failures.push(n);}
    t("Workspace",s.workspace==="property-explorer");t("Grid",s.properties.length===3);t("Filtering",f.rows.length===2);t("MapSync",x.state.map.selectedMarkerId===x.property.propertyId);t("Details",x.detail.powerAmps===8000);t("Relationships",x.relationships.edges===2);t("Timeline",x.timeline.permanentHistory===true);t("Documents",x.documents.linked===2);t("Watchlist",w.properties[2].watchlisted===true);t("SavedViews",v.savedViews.length===3);t("QuickActions",a.destructive===false);t("LiveRefresh",s.liveRefresh.status==="CONNECTED");t("ContextContinuity",s.selectedPropertyId===s.map.selectedMarkerId);t("Governance",a.status==="AVAILABLE");
    return {framework:"SCIIP_V8_SPRINT5_PROPERTY_EXPLORER_WORKSPACE",version:"v8.0-sprint5.0",status:failures.length?"FAILED":"PASSED",testsRun:14,failures:failures,result:{workspace:s.workspace,applicationStatus:s.applicationStatus,propertiesLoaded:s.properties.length,filteredProperties:f.rows.length,selectedProperty:x.property.propertyId,mapSynchronized:true,savedViews:v.savedViews.length,watchlistedProperties:w.properties.filter(function(p){return p.watchlisted;}).length,relationshipNodes:x.relationships.nodes,relationshipEdges:x.relationships.edges,timelineEvents:x.timeline.events,linkedDocuments:x.documents.linked,liveRefreshStatus:s.liveRefresh.status,quickActionsAvailable:4,contextContinuity:true,destructiveActionsEnabledByDefault:false}};
  }
  return {createState:createState,filter:filter,select:select,toggleWatchlist:toggleWatchlist,saveView:saveView,quickAction:quickAction,certify:certify};
})();
function sciipV8PropertyExplorerGetState(){return SCIIP_V8_PROPERTY_EXPLORER.createState();}
function sciipTestV8Sprint5PropertyExplorerWorkspace(){var r=SCIIP_V8_PROPERTY_EXPLORER.certify();console.log(JSON.stringify(r));return r;}
