var SCIIP_S33_APPLICATION=(function(){'use strict';var VERSION='v7.0-integration-sprint-33.0';
function definition(){return {id:'enterprise-digital-strategy-officer',name:'Enterprise Digital Strategy Officer',version:VERSION,dependencies:['enterprise-digital-ceo','enterprise-autonomous-planning-execution'],services:['enterprise-digital-strategy-officer'],queries:['enterprise-digital-strategy-officer-query'],events:['EXECUTIVE_RECOMMENDATION_CREATED','EXECUTIVE_APPROVAL_ROUTED','EXECUTIVE_COMMAND_ISSUED'],stateBindings:['executiveSuite','enterprise_digital_strategy_officer'],workspaces:['enterprise-digital-strategy-officer'],tests:['sciipTestV7IntegrationSprint33'],liveHandler:'sciipEnterpriseDigitalStrategyOfficerHeartbeatV7',queryHandler:'sciipEnterpriseDigitalStrategyOfficerQueryV7'};}
function run(r){r=r||{};var synthesis=SCIIP_S33_STRATEGY_SYNTHESIS_ENGINE.synthesize(r),scenarios=SCIIP_S33_LONG_RANGE_SCENARIO_ENGINE.compare(r),initiatives=SCIIP_S33_STRATEGIC_INITIATIVE_ENGINE.prioritize(r),scorecard=SCIIP_S33_STRATEGY_SCORECARD.calculate({synthesis:synthesis,scenarios:scenarios,initiatives:initiatives}),workspace=SCIIP_S33_EXECUTIVE_STRATEGY_WORKSPACE.build({synthesis:synthesis,scenarios:scenarios,initiatives:initiatives,scorecard:scorecard});return {version:VERSION,status:'AVAILABLE',synthesis:synthesis,scenarios:scenarios,initiatives:initiatives,scorecard:scorecard,workspace:workspace};}
function names(s,ks){var raw=[];for(var i=0;i<ks.length;i++)if(s&&s[ks[i]]!=null){raw=s[ks[i]];break;}if(Array.isArray(raw))return raw.map(function(x){return typeof x==='string'?x:String((x&&(x.name||x.id))||'');});return raw&&typeof raw==='object'?Object.keys(raw):[];}
function wire(){var o={status:'PARTIAL',registry:false,assembly:false,queryRegistered:false,liveServiceRegistered:false,sharedState:typeof SCIIP_APP_STATE!=='undefined',eventBus:typeof SCIIP_APP_EVENTS!=='undefined',registrationMode:[]};try{o.registry=SCIIP_PLATFORM_REGISTRY.register(definition()).status!=='CONFLICT';}catch(e){}try{o.assembly=SCIIP_PLATFORM_SELF_ASSEMBLY.assemble({source:'SPRINT_33'}).status!=='FAILED';if(o.assembly)o.registrationMode.push('SELF_ASSEMBLY');}catch(e2){}var qs=typeof SCIIP_QUERY_ENGINE!=='undefined'&&SCIIP_QUERY_ENGINE.snapshot?SCIIP_QUERY_ENGINE.snapshot():{},ls=typeof SCIIP_LIVE_RUNTIME!=='undefined'&&SCIIP_LIVE_RUNTIME.snapshot?SCIIP_LIVE_RUNTIME.snapshot():{};o.queryRegistered=names(qs,['registeredQueries','queries','registry']).indexOf('enterprise-digital-strategy-officer-query')!==-1;o.liveServiceRegistered=names(ls,['services','registry']).indexOf('enterprise-digital-strategy-officer')!==-1;if(!o.queryRegistered&&typeof SCIIP_QUERY_ENGINE!=='undefined'&&SCIIP_QUERY_ENGINE.register){SCIIP_QUERY_ENGINE.register('enterprise-digital-strategy-officer-query',sciipEnterpriseDigitalStrategyOfficerQueryV7,{capability:definition().id});o.queryRegistered=true;}if(!o.liveServiceRegistered&&typeof SCIIP_LIVE_RUNTIME!=='undefined'&&SCIIP_LIVE_RUNTIME.register){SCIIP_LIVE_RUNTIME.register('enterprise-digital-strategy-officer',sciipEnterpriseDigitalStrategyOfficerHeartbeatV7,{capability:definition().id});o.liveServiceRegistered=true;}if(o.registry&&o.assembly&&o.queryRegistered&&o.liveServiceRegistered&&o.sharedState&&o.eventBus)o.status='WIRED';return o;}
return {VERSION:VERSION,run:run,wire:wire,platformDefinition:definition};})();
function sciipEnterpriseDigitalStrategyOfficerQueryV7(r){return SCIIP_S33_APPLICATION.run(r||{});}function sciipEnterpriseDigitalStrategyOfficerHeartbeatV7(){return {status:'AVAILABLE',version:'v7.0-integration-sprint-33.0',workspace:'enterprise-digital-strategy-officer',generatedAt:new Date().toISOString()};}

var SCIIP_S33_APPLICATION=SCIIP_S33_APPLICATION;
