/** Explicit Apps Script regression tests for Sprint 5A. */
function sciipTestV7AutonomousMarketMonitor(){SCIIP_AUTONOMOUS_MARKET_MONITOR.reset();SCIIP_AUTONOMOUS_MARKET_MONITOR.registerRule({id:'VACANCY_HIGH',metric:'vacancy',operator:'GTE',threshold:8,severity:'WARNING'});var r=SCIIP_AUTONOMOUS_MARKET_MONITOR.observe({marketId:'IE-WEST',metric:'vacancy',value:8.5});var s=SCIIP_AUTONOMOUS_MARKET_MONITOR.snapshot();if(r.alertsCreated<1||s.alerts.length!==1)throw new Error('Autonomous market monitor failed: '+JSON.stringify({r:r,s:s}));return {test:'AutonomousMarketMonitor',status:'PASSED',observations:s.observations.length,alerts:s.alerts.length};}
function sciipTestV7ContinuousPortfolioScoring(){var r=SCIIP_CONTINUOUS_PORTFOLIO_SCORING.run({assets:[{id:'P-A',suitability:90,infrastructure:85,labor:70,market:75,tenantFit:88,risk:20},{id:'P-B',suitability:70,infrastructure:65,labor:80,market:70,tenantFit:60,risk:35}]});if(r.count!==2||r.rankings[0].entityId!=='P-A')throw new Error('Continuous portfolio scoring failed: '+JSON.stringify(r));return {test:'ContinuousPortfolioScoring',status:'PASSED',winner:r.rankings[0].entityId,score:r.rankings[0].score};}
function sciipTestV7PredictiveMarketIndicators(){var r=SCIIP_PREDICTIVE_MARKET_INDICATORS.forecast({values:[7.8,7.5,7.2,6.9],horizon:3});if(r.direction!=='DOWN'||r.forecast.length!==3)throw new Error('Predictive indicators failed: '+JSON.stringify(r));return {test:'PredictiveMarketIndicators',status:'PASSED',direction:r.direction,slope:r.slope};}
function sciipTestV7SiteSelectionTenantMatching(){var properties=[{id:'P-A',buildingSf:500000,powerAmps:5000,landAcres:25,suitability:92,infrastructure:90,labor:75,market:80,costIndex:40,capabilities:['aerospace','defense'],locationScore:85},{id:'P-B',buildingSf:200000,powerAmps:2000,landAcres:10,suitability:70,infrastructure:65,labor:80,market:75,costIndex:30,capabilities:['logistics'],locationScore:70}],s=SCIIP_INDUSTRIAL_SITE_SELECTION.select({requirements:{minSf:300000,minPower:4000},properties:properties}),m=SCIIP_TENANT_COMPANY_MATCHING.match({company:{id:'C-1',capabilities:['aerospace','defense'],requiredPower:4000,requiredSf:400000},properties:properties});if(!s.winner||s.winner.entityId!=='P-A'||!m.winner||m.winner.entityId!=='P-A')throw new Error('Selection/matching failed: '+JSON.stringify({s:s,m:m}));return {test:'SiteSelectionTenantMatching',status:'PASSED',site:s.winner.entityId,tenantFit:m.winner.score};}
function sciipTestV7ExecutiveBriefing(){var r=SCIIP_EXECUTIVE_BRIEFING_ENGINE.generate({market:{direction:'UP'},portfolio:{count:2},alerts:[{id:'A-1'}],recommendations:[{id:'R-1'}]});if(r.status!=='COMPLETED'||r.sections.length!==4||r.grounding.externalModelInvoked!==false)throw new Error('Executive briefing failed: '+JSON.stringify(r));return {test:'ExecutiveBriefing',status:'PASSED',sections:r.sections.length,deterministic:r.grounding.deterministic};}
function sciipTestV7AutonomousOrchestration(){var r=SCIIP_SPRINT5A_AUTONOMOUS_ORCHESTRATOR.run({marketSeries:[8,7.5,7],assets:[{id:'P-A',suitability:90,infrastructure:90,labor:75,market:80,tenantFit:85,risk:20}],properties:[{id:'P-A',buildingSf:500000,powerAmps:5000,landAcres:25,suitability:90,infrastructure:90,labor:75,market:80,costIndex:40,capabilities:['defense'],locationScore:85}],company:{id:'C-1',capabilities:['defense'],requiredPower:4000,requiredSf:400000},requirements:{minSf:300000,minPower:4000}});if(r.status!=='COMPLETED'||!r.selection.winner||!r.matching.winner||r.briefing.status!=='COMPLETED')throw new Error('Autonomous orchestration failed: '+JSON.stringify(r));return {test:'AutonomousOrchestration',status:'PASSED',site:r.selection.winner.entityId,match:r.matching.winner.entityId,forecast:r.forecast.direction};}
function sciipTestV7Sprint5APlatformWiring(){SCIIP_SPRINT5A_PLATFORM_BOOTSTRAP.declare();var a=SCIIP_PLATFORM_SELF_ASSEMBLY.assemble({source:'SPRINT5A_TEST'}),q=SCIIP_PLATFORM_ADAPTERS.queryNames(),l=SCIIP_PLATFORM_ADAPTERS.liveNames(),ok=q.indexOf('autonomous-industrial-intelligence')>=0&&l.indexOf('autonomous-industrial-intelligence')>=0;if(a.status!=='WIRED'||!ok)throw new Error('Sprint 5A platform wiring failed: '+JSON.stringify({assembly:a,queries:q,services:l}));return {test:'PlatformWiring',status:'PASSED',assemblyStatus:a.status,queryRegistered:true,liveServiceRegistered:true};}
function sciipTestV7IntegrationSprint5A(){var tests=[sciipTestV7AutonomousMarketMonitor(),sciipTestV7ContinuousPortfolioScoring(),sciipTestV7PredictiveMarketIndicators(),sciipTestV7SiteSelectionTenantMatching(),sciipTestV7ExecutiveBriefing(),sciipTestV7AutonomousOrchestration(),sciipTestV7Sprint5APlatformWiring()];var output={framework:'SCIIP_V7_INTEGRATION_SPRINT_5A_AUTONOMOUS_INDUSTRIAL_INTELLIGENCE',version:'v7.0-integration-sprint-5a',status:'PASSED',testsRun:tests.length,tests:tests,generatedAt:new Date().toISOString()};console.log(JSON.stringify(output));return output;}
