/** Explicit Apps Script regression tests for Sprint 4B. */
function sciipTestV7PlatformRegistry(){
 SCIIP_PLATFORM_REGISTRY.register({id:'test-foundation',name:'Test Foundation',services:['test-foundation-live'],queries:['test-foundation-query'],tests:['explicit'],metadata:{compilerV2:true,noProcessors:true}});
 SCIIP_PLATFORM_REGISTRY.register({id:'test-dependent',name:'Test Dependent',dependencies:['test-foundation'],tests:['explicit'],metadata:{compilerV2:true,noProcessors:true}});
 var s=SCIIP_PLATFORM_REGISTRY.snapshot();if(s.status!=='AVAILABLE'||s.dependencyOrder.indexOf('test-foundation')>s.dependencyOrder.indexOf('test-dependent'))throw new Error('Platform Registry failed: '+JSON.stringify(s));
 return {test:'PlatformRegistry',status:'PASSED',capabilities:s.count,dependencyOrder:s.dependencyOrder.slice(-2)};
}
function sciipTestV7PlatformAdapters(){var q=SCIIP_PLATFORM_ADAPTERS.registerQuery('adapter-test-query',function(p){return p||{};}),l=SCIIP_PLATFORM_ADAPTERS.registerLive('adapter-test-live',function(p){return p||{};},{domain:'TEST'});if(!q.registered||!l.registered)throw new Error('Platform adapters failed: '+JSON.stringify({q:q,l:l}));return {test:'PlatformAdapters',status:'PASSED',queryRegistered:q.registered,liveRegistered:l.registered};}
function sciipTestV7PlatformSelfAssembly(){SCIIP_PLATFORM_BOOTSTRAP.declare();var r=SCIIP_PLATFORM_SELF_ASSEMBLY.assemble({source:'TEST'});if(r.status!=='WIRED')throw new Error('Platform self-assembly failed: '+JSON.stringify(r));return {test:'PlatformSelfAssembly',status:'PASSED',runId:r.id,capabilities:r.results.length};}
function sciipTestV7PlatformCertifier(){var r=SCIIP_PLATFORM_CERTIFIER.certify({assemble:true});if(r.status!=='PASSED')throw new Error('Platform certification failed: '+JSON.stringify(r));return {test:'PlatformCertifier',status:'PASSED',capabilities:r.capabilitiesRun,failures:r.failures.length};}
function sciipTestV7DuplicateSafety(){var d={id:'duplicate-safe-capability',name:'Duplicate Safe',tests:['explicit'],metadata:{compilerV2:true,noProcessors:true}},a=SCIIP_PLATFORM_REGISTRY.register(d),b=SCIIP_PLATFORM_REGISTRY.register(d);if(a.status!=='REGISTERED'||b.status!=='DUPLICATE_SAFE')throw new Error('Registry duplicate safety failed.');return {test:'DuplicateSafety',status:'PASSED',first:a.status,second:b.status};}
function sciipTestV7IntegrationSprint4B(){var tests=[sciipTestV7PlatformRegistry(),sciipTestV7PlatformAdapters(),sciipTestV7PlatformSelfAssembly(),sciipTestV7PlatformCertifier(),sciipTestV7DuplicateSafety()];var output={framework:'SCIIP_V7_INTEGRATION_SPRINT_4B_PLATFORM_SELF_ASSEMBLY_CERTIFICATION',version:'v7.0-integration-sprint-4b',status:'PASSED',testsRun:tests.length,tests:tests,generatedAt:new Date().toISOString()};console.log(JSON.stringify(output));return output;}
