/** SCIIP_OS v7.0 Sprint 4A — retryable service wiring. */
var SCIIP_INDUSTRIAL_INTELLIGENCE_WIRING=(function(){'use strict';var VERSION='v7.0-integration-sprint-4a';
function serviceNames(snapshot){var s=snapshot&&snapshot.services||[];return s.map(function(x){return typeof x==='string'?x:String(x.name||x.id||x.service||'');});}
function ensure(){var out={version:VERSION,status:'PARTIAL',queryRegistered:false,liveServiceRegistered:false,capabilityBuilderAvailable:typeof SCIIP_CAPABILITY_BUILDER!=='undefined',errors:[]};
 try{if(typeof SCIIP_QUERY_ENGINE!=='undefined'){var qs=SCIIP_QUERY_ENGINE.snapshot?SCIIP_QUERY_ENGINE.snapshot():{};var names=(qs.queries||[]).map(function(x){return typeof x==='string'?x:String(x.name||x.id||'');});if(names.indexOf('industrial-intelligence')<0&&SCIIP_QUERY_ENGINE.register)SCIIP_QUERY_ENGINE.register('industrial-intelligence',function(req){return SCIIP_INDUSTRIAL_INTELLIGENCE_WORKSPACE.snapshot(req||{});});qs=SCIIP_QUERY_ENGINE.snapshot?SCIIP_QUERY_ENGINE.snapshot():{};names=(qs.queries||[]).map(function(x){return typeof x==='string'?x:String(x.name||x.id||'');});out.queryRegistered=names.indexOf('industrial-intelligence')>=0;}}catch(e){out.errors.push('query:'+e);}
 try{if(typeof SCIIP_LIVE_RUNTIME!=='undefined'){var ls=SCIIP_LIVE_RUNTIME.snapshot?SCIIP_LIVE_RUNTIME.snapshot():{},names2=serviceNames(ls);if(names2.indexOf('industrial-intelligence')<0&&SCIIP_LIVE_RUNTIME.register)SCIIP_LIVE_RUNTIME.register('industrial-intelligence',function(payload){return SCIIP_INDUSTRIAL_INTELLIGENCE_WORKSPACE.snapshot(payload||{});},{domain:'INDUSTRIAL_INTELLIGENCE'});ls=SCIIP_LIVE_RUNTIME.snapshot?SCIIP_LIVE_RUNTIME.snapshot():{};names2=serviceNames(ls);out.liveServiceRegistered=names2.indexOf('industrial-intelligence')>=0;}}catch(e2){out.errors.push('live:'+e2);}
 out.status=out.queryRegistered&&out.liveServiceRegistered&&out.capabilityBuilderAvailable?'WIRED':'PARTIAL';return out;}
 return {VERSION:VERSION,ensure:ensure};})();
function sciipIndustrialIntelligenceWiringV7(){return SCIIP_INDUSTRIAL_INTELLIGENCE_WIRING.ensure();}
