function sciipTestV7Epic3Sprint8(){
  var failures=[];
  function check(name,ok){if(!ok)failures.push(name);}
  var input={minimumScore:55,minimumEvidence:1,signals:[
    {businessKey:'TENANT|P-1|T-1|2026-07-17',type:'TENANT_REPRESENTATION',title:'Aerospace tenant expansion near powered facility',propertyId:'P-1',tenantId:'T-1',marketId:'SOUTH-BAY',demandScore:95,propertyFitScore:92,networkScore:88,timingScore:90,confidence:90,riskScore:10,observedAt:'2026-07-17',recommendedAction:'CONTACT_TENANT_AND_POSITION_PROPERTY',evidence:[{sourceId:'REL-1',sourceType:'GRAPH',observedAt:'2026-07-17',reference:'Two-hop aerospace expansion relationship',confidence:92}]},
    {businessKey:'ACQ|P-2|2026-07-17',type:'ACQUISITION',title:'Underpriced infill acquisition',propertyId:'P-2',marketId:'LA-BASIN',demandScore:85,propertyFitScore:82,networkScore:75,timingScore:80,confidence:80,riskScore:20,observedAt:'2026-07-17',recommendedAction:'UNDERWRITE_ACQUISITION',evidence:[{sourceId:'TX-2',sourceType:'TRANSACTION',observedAt:'2026-07-17',reference:'Pricing dislocation',confidence:80}]},
    {businessKey:'LOW|P-3|2026-07-17',title:'Weak signal',propertyId:'P-3',demandScore:10,propertyFitScore:20,networkScore:10,timingScore:10,confidence:20,riskScore:80,observedAt:'2026-07-17',evidence:[{sourceId:'M-1',sourceType:'MARKET',reference:'Weak'}]},
    {businessKey:'TENANT|P-1|T-1|2026-07-17',title:'Duplicate',propertyId:'P-1',tenantId:'T-1',demandScore:99,propertyFitScore:99,networkScore:99,timingScore:99,confidence:99,evidence:[{sourceId:'DUP'}]}
  ]};
  var d=SCIIP_AUTONOMOUS_OPPORTUNITY_DISCOVERY.discover(input);check('DiscoveryCount',d.opportunities.length===2);check('RejectCount',d.rejected.length===1);check('Ranking',d.opportunities[0].score>=d.opportunities[1].score);check('Governance',d.reviewRequired===true&&d.destructiveCommitEnabled===false);var rec=SCIIP_AUTONOMOUS_OPPORTUNITY_DISCOVERY.recommendations(d);check('Recommendations',rec.length===2&&rec[0].approvalRequired===true);var persisted=SCIIP_AUTONOMOUS_OPPORTUNITY_PERSISTENCE.append([],d);var persisted2=SCIIP_AUTONOMOUS_OPPORTUNITY_PERSISTENCE.append(persisted.rows,d);check('Persistence',persisted.recordsCreated===2&&persisted2.skippedDuplicate===2);var app=SCIIP_AUTONOMOUS_OPPORTUNITY_APPLICATION.run(input);check('NorthStar',app.capabilities.indexOf('ACT')!==-1&&app.northStar.indexOf('operating system for industrial real estate')!==-1);var changes=SCIIP_AUTONOMOUS_OPPORTUNITY_DISCOVERY.detectChanges([],d.opportunities);check('ChangeDetection',changes.count===2);
  return {framework:'SCIIP_V7_EPIC_3_SPRINT_8_AUTONOMOUS_OPPORTUNITY_DISCOVERY',version:'v7.0-epic3-sprint8.0',status:failures.length?'FAILED':'PASSED',testsRun:8,failures:failures,result:{opportunities:d.opportunities.length,rejected:d.rejected.length,topOpportunity:d.opportunities[0]&&d.opportunities[0].id,topScore:d.opportunities[0]&&d.opportunities[0].score,recommendations:rec.length,changes:changes.count,persisted:persisted.recordsCreated,workspace:app.workspace,reviewRequired:true,destructiveCommitEnabled:false}};
}
