/** Append-only persistence facade for governed relationship records. */
var SCIIP_RELATIONSHIP_INTELLIGENCE_STORE=(function(){'use strict';
var SHEET='SCIIP_RELATIONSHIP_LEDGER',HEADERS=['relationshipId','schemaVersion','relationshipType','fromId','fromType','toId','toType','direction','status','effectiveAt','endedAt','weight','confidence','attributesJson','sourceJson','evidenceJson','recordedAt','reviewStatus','appendOnly'];
function sheet_(){var ss=SpreadsheetApp.getActiveSpreadsheet();if(!ss)throw new Error('NO_ACTIVE_SPREADSHEET');var sh=ss.getSheetByName(SHEET)||ss.insertSheet(SHEET);if(sh.getLastRow()===0)sh.getRange(1,1,1,HEADERS.length).setValues([HEADERS]);return sh;}
function existing_(sh){if(sh.getLastRow()<2)return{};var v=sh.getRange(2,1,sh.getLastRow()-1,1).getValues(),o={};v.forEach(function(r){o[String(r[0])]=true;});return o;}
function append(items,approval){if(!approval||String(approval.status).toUpperCase()!=='APPROVED')return{status:'REVIEW_REQUIRED',created:0,received:(items||[]).length,destructiveWrite:false};var sh=sheet_(),seen=existing_(sh),rows=[];SCIIP_RELATIONSHIP_INTELLIGENCE.normalize(items||[]).forEach(function(e){if(seen[e.relationshipId])return;rows.push([e.relationshipId,e.schemaVersion,e.relationshipType,e.fromId,e.fromType,e.toId,e.toType,e.direction,e.status,e.effectiveAt,e.endedAt,e.weight,e.confidence,JSON.stringify(e.attributes||{}),JSON.stringify(e.source||{}),JSON.stringify(e.evidence||[]),e.recordedAt,e.reviewStatus,true]);seen[e.relationshipId]=true;});if(rows.length)sh.getRange(sh.getLastRow()+1,1,rows.length,HEADERS.length).setValues(rows);return{status:'COMMITTED',created:rows.length,duplicates:(items||[]).length-rows.length,sheet:SHEET,appendOnly:true,destructiveWrite:false};}
function read(){var ss=SpreadsheetApp.getActiveSpreadsheet(),sh=ss&&ss.getSheetByName(SHEET);if(!sh||sh.getLastRow()<2)return[];var v=sh.getDataRange().getValues(),h=v.shift().map(String);return v.map(function(r){var o={};h.forEach(function(k,i){o[k]=r[i];});['attributesJson','sourceJson','evidenceJson'].forEach(function(k){try{o[k.replace('Json','')]=JSON.parse(o[k]||'null');}catch(e){o[k.replace('Json','')]=null;}});return o;});}
function workspace(){var r=read(),c=SCIIP_RELATIONSHIP_INTELLIGENCE.centrality(r),top=Object.keys(c).map(function(k){return c[k];}).sort(function(a,b){return b.score-a.score;}).slice(0,10);return{status:'AVAILABLE',relationships:r.slice(-100).reverse(),counts:{relationships:r.length,entities:Object.keys(SCIIP_RELATIONSHIP_INTELLIGENCE.graph(r).nodes).length},centrality:top,components:SCIIP_RELATIONSHIP_INTELLIGENCE.components(r)};}
return{append:append,read:read,workspace:workspace};})();
function sciipPersistRelationships(items,approval){return SCIIP_RELATIONSHIP_INTELLIGENCE_STORE.append(items||[],approval||{});}
function sciipRelationshipIntelligenceWorkspace(){try{return SCIIP_RELATIONSHIP_INTELLIGENCE_STORE.workspace();}catch(e){return{status:'READY',relationships:[],counts:{relationships:0,entities:0},centrality:[],components:[],diagnostic:String(e.message||e)};}}
