const decisions=[];
const clone=value=>JSON.parse(JSON.stringify(value));
const stable=value=>JSON.stringify(value,Object.keys(value||{}).sort());
const hash=text=>{let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')};
export function createDecisionId(input={}){return `decision-${hash(stable({assignmentId:input.assignmentId||'enterprise',type:input.type||'RECOMMENDATION',subjectId:input.subjectId||'general',evidenceIds:[...(input.evidenceIds||[])].sort()}))}`}
export function recordDecision(input={}){if(!input.actorId)throw new Error('actorId is required');if(!input.recommendation)throw new Error('recommendation is required');const decisionId=input.decisionId||createDecisionId(input);const existing=decisions.find(x=>x.decisionId===decisionId);if(existing)return clone(existing);const row={decisionId,assignmentId:input.assignmentId||'enterprise',subjectId:input.subjectId||null,type:input.type||'RECOMMENDATION',recommendation:input.recommendation,alternatives:clone(input.alternatives||[]),evidenceIds:[...(input.evidenceIds||[])],confidence:Number(input.confidence||0),status:'PENDING_REVIEW',actorId:input.actorId,createdAt:input.createdAt||new Date().toISOString(),brokerDecision:null,outcome:null};decisions.push(Object.freeze(row));return clone(row)}
export function decide(decisionId,{actorId,decision,rationale='',decidedAt=new Date().toISOString()}={}){if(!actorId)throw new Error('actorId is required');if(!['APPROVED','REJECTED','DEFERRED'].includes(decision))throw new Error('invalid decision');const source=decisions.find(x=>x.decisionId===decisionId);if(!source)throw new Error('decision not found');const event={...clone(source),ledgerEventId:`${decisionId}-${decisions.length+1}`,status:'DECIDED',brokerDecision:{decision,rationale,actorId,decidedAt}};decisions.push(Object.freeze(event));return clone(event)}
export function recordOutcome(decisionId,{actorId,outcome,metrics={},recordedAt=new Date().toISOString()}={}){if(!actorId||!outcome)throw new Error('actorId and outcome are required');const source=[...decisions].reverse().find(x=>x.decisionId===decisionId);if(!source)throw new Error('decision not found');const event={...clone(source),ledgerEventId:`${decisionId}-${decisions.length+1}`,status:'OUTCOME_RECORDED',outcome:{outcome,metrics:clone(metrics),actorId,recordedAt}};decisions.push(Object.freeze(event));return clone(event)}
export function readDecisionLedger({assignmentId}={}){return clone(assignmentId?decisions.filter(x=>x.assignmentId===assignmentId):decisions)}
export function resetDecisionLedger(){decisions.length=0}
