var SCIIP_S32_APPLICATION=(function(){'use strict';var VERSION='v7.0-integration-sprint-32.0';
function definition(){return {id:'enterprise-digital-cfo',name:'Enterprise Digital CFO',version:VERSION,dependencies:['enterprise-digital-ceo','enterprise-financial-planning-forecasting'],services:['enterprise-digital-cfo'],queries:['enterprise-digital-cfo-query'],events:['EXECUTIVE_RECOMMENDATION_CREATED','EXECUTIVE_APPROVAL_ROUTED','EXECUTIVE_COMMAND_ISSUED'],stateBindings:['executiveSuite','enterprise_digital_cfo'],workspaces:['enterprise-digital-cfo'],tests:['sciipTestV7IntegrationSprint32'],liveHandler:'sciipEnterpriseDigitalCfoHeartbeatV7',queryHandler:'sciipEnterpriseDigitalCfoQueryV7'};}
function run(r){r=r||{};var forecast=SCIIP_S32_MULTI_YEAR_FORECAST_ENGINE.forecast(r),cashFlow=SCIIP_S32_CASH_FLOW_OPTIMIZATION_ENGINE.optimize(r),valuation=SCIIP_S32_PORTFOLIO_VALUATION_ENGINE.value(r),scorecard=SCIIP_S32_CFO_SCORECARD.calculate({forecast:forecast,cashFlow:cashFlow,valuation:valuation}),workspace=SCIIP_S32_EXECUTIVE_CFO_WORKSPACE.build({forecast:forecast,cashFlow:cashFlow,valuation:valuation,scorecard:scorecard});return {version:VERSION,status:'AVAILABLE',forecast:forecast,cashFlow:cashFlow,valuation:valuation,scorecard:scorecard,workspace:workspace};}
function names(s,ks){var raw=[];for(var i=0;i<ks.length;i++)if(s&&s[ks[i]]!=null){raw=s[ks[i]];break;}if(Array.isArray(raw))return raw.map(function(x){return typeof x==='string'?x:String((x&&(x.name||x.id))||'');});return raw&&typeof raw==='object'?Object.keys(raw):[];}
function wire(){var o={status:'PARTIAL',registry:false,assembly:false,queryRegistered:false,liveServiceRegistered:false,sharedState:typeof SCIIP_APP_STATE!=='undefined',eventBus:typeof SCIIP_APP_EVENTS!=='undefined',registrationMode:[]};try{o.registry=SCIIP_PLATFORM_REGISTRY.register(definition()).status!=='CONFLICT';}catch(e){}try{o.assembly=SCIIP_PLATFORM_SELF_ASSEMBLY.assemble({source:'SPRINT_32'}).status!=='FAILED';if(o.assembly)o.registrationMode.push('SELF_ASSEMBLY');}catch(e2){}var qs=typeof SCIIP_QUERY_ENGINE!=='undefined'&&SCIIP_QUERY_ENGINE.snapshot?SCIIP_QUERY_ENGINE.snapshot():{},ls=typeof SCIIP_LIVE_RUNTIME!=='undefined'&&SCIIP_LIVE_RUNTIME.snapshot?SCIIP_LIVE_RUNTIME.snapshot():{};o.queryRegistered=names(qs,['registeredQueries','queries','registry']).indexOf('enterprise-digital-cfo-query')!==-1;o.liveServiceRegistered=names(ls,['services','registry']).indexOf('enterprise-digital-cfo')!==-1;if(!o.queryRegistered&&typeof SCIIP_QUERY_ENGINE!=='undefined'&&SCIIP_QUERY_ENGINE.register){SCIIP_QUERY_ENGINE.register('enterprise-digital-cfo-query',sciipEnterpriseDigitalCfoQueryV7,{capability:definition().id});o.queryRegistered=true;}if(!o.liveServiceRegistered&&typeof SCIIP_LIVE_RUNTIME!=='undefined'&&SCIIP_LIVE_RUNTIME.register){SCIIP_LIVE_RUNTIME.register('enterprise-digital-cfo',sciipEnterpriseDigitalCfoHeartbeatV7,{capability:definition().id});o.liveServiceRegistered=true;}if(o.registry&&o.assembly&&o.queryRegistered&&o.liveServiceRegistered&&o.sharedState&&o.eventBus)o.status='WIRED';return o;}
return {VERSION:VERSION,run:run,wire:wire,platformDefinition:definition};})();
function sciipEnterpriseDigitalCfoQueryV7(r){return SCIIP_S32_APPLICATION.run(r||{});}function sciipEnterpriseDigitalCfoHeartbeatV7(){return {status:'AVAILABLE',version:'v7.0-integration-sprint-32.0',workspace:'enterprise-digital-cfo',generatedAt:new Date().toISOString()};}

var SCIIP_S32_APPLICATION=SCIIP_S32_APPLICATION;
