/* ==========================================================
   SCIIP_OS
   Module: Queue
   File: WorkQueue.gs

   Purpose:
   SCIIP Work Queue

   Queues work generated by observations,
   commands, events, and processors.

   Supports autonomous processing and
   future AI-driven workflows.

   Source of Truth:
   GitHub

   Runtime:
   Google Apps Script
========================================================== */

const SCIIP_WORK_QUEUE_SHEET =
  'WORK_QUEUE';

/**
 * Returns work queue sheet.
 *
 * @returns {GoogleAppsScript.Spreadsheet.Sheet}
 */
function sciipGetWorkQueueSheet() {
  return sciipGetOrCreateSheet(
    SCIIP_WORK_QUEUE_SHEET
  );
}

/**
 * Initializes queue sheet.
 */
function sciipInitializeWorkQueue() {
  const sheet =
    sciipGetWorkQueueSheet();

  if (sheet.getLastRow() > 0) {
    return;
  }

  sheet.appendRow([
    'Queue_ID',
    'Task_Type',
    'Asset_ID',
    'Status',
    'Priority',
    'Payload',
    'Created_At',
    'Started_At',
    'Completed_At'
  ]);
}

/**
 * Enqueues a task.
 *
 * @param {Object} task
 * @returns {Object}
 */
function sciipQueueEnqueue(task) {
  sciipInitializeWorkQueue();

  const queueId =
    'QUEUE_' +
    sciipUuid()
      .replace(/-/g, '')
      .substring(0, 16)
      .toUpperCase();

  sciipAppendRow(
    SCIIP_WORK_QUEUE_SHEET,
    [
      queueId,
      task.taskType || 'UNKNOWN',
      task.assetId || '',
      'PENDING',
      task.priority || 100,
      sciipSafeJson(task.payload || {}),
      sciipNowIso(),
      '',
      ''
    ]
  );

  return {
    queueId: queueId,
    status: 'PENDING'
  };
}

/**
 * Returns pending tasks.
 *
 * @returns {Array}
 */
function sciipQueuePending() {
  const rows =
    sciipGetSheetValues(
      SCIIP_WORK_QUEUE_SHEET
    );

  if (rows.length < 2) {
    return [];
  }

  const headers = rows[0];
  const statusIndex =
    headers.indexOf('Status');

  return rows
    .slice(1)
    .filter(function(row) {
      return row[statusIndex] === 'PENDING';
    })
    .map(function(row) {

      const obj = {};

      headers.forEach(function(header, index) {
        obj[header] = row[index];
      });

      return obj;
    });
}

/**
 * Returns queue statistics.
 *
 * @returns {Object}
 */
function sciipQueueStats() {
  const rows =
    sciipGetSheetValues(
      SCIIP_WORK_QUEUE_SHEET
    );

  const pending =
    sciipQueuePending().length;

  return {
    queueRecords:
      rows.length > 0
        ? rows.length - 1
        : 0,

    pendingTasks:
      pending,

    generatedAt:
      sciipNowIso()
  };
}