var SCIIP_V8_COMPANY_EXPLORER=(function(){
  function clone_(v){return JSON.parse(JSON.stringify(v));}
  function companies_(){return [
    {companyId:"COMP-ABL-SPACE",name:"ABL Space Systems",companyType:"TENANT",sector:"AEROSPACE",naics:"336414",sic:"3764",headquarters:"El Segundo, CA",executives:[{name:"Harry O'Hanley",title:"Chief Executive Officer"},{name:"Operations Executive",title:"VP Operations"}],facilityRequirements:{minPowerAmps:4000,minClearHeightFt:32,minBuildingSf:150000,minTrailerParking:40,yardRequired:true,craneRequired:true},properties:[{propertyId:"PROP-ABL-1",relationship:"OCCUPIES"},{propertyId:"PROP-ABL-2",relationship:"OCCUPIES"}],documents:3,timelineEvents:4,watchlisted:true},
    {companyId:"COMP-AEROJET-ROCKETDYNE",name:"Aerojet Rocketdyne",companyType:"TENANT",sector:"AEROSPACE_DEFENSE",naics:"336415",sic:"3761",headquarters:"El Segundo, CA",executives:[{name:"Division President",title:"President"},{name:"Real Estate Executive",title:"Director, Real Estate"}],facilityRequirements:{minPowerAmps:6000,minClearHeightFt:28,minBuildingSf:250000,minTrailerParking:25,yardRequired:true,craneRequired:true},properties:[{propertyId:"PROP-AR-1",relationship:"OCCUPIES"},{propertyId:"PROP-AR-2",relationship:"OCCUPIES"},{propertyId:"PROP-AR-3",relationship:"OCCUPIES"}],documents:5,timelineEvents:6,watchlisted:false},
    {companyId:"COMP-BROOKFIELD",name:"Brookfield Properties",companyType:"OWNER",sector:"INDUSTRIAL_REAL_ESTATE",naics:"531312",sic:"6512",headquarters:"New York, NY",executives:[{name:"Industrial Executive",title:"Managing Partner"},{name:"Southern California Executive",title:"Vice President"}],facilityRequirements:{minPowerAmps:0,minClearHeightFt:0,minBuildingSf:0,minTrailerParking:0,yardRequired:false,craneRequired:false},properties:[{propertyId:"PROP-RIALTO-2125-LOWELL",relationship:"OWNS"},{propertyId:"PROP-BP-2",relationship:"OWNS"}],documents:4,timelineEvents:5,watchlisted:true}
  ];}
  function createState(){var c=companies_();return {version:"v8.0-sprint6.0",workspace:"company-explorer",applicationStatus:"OPERATIONAL",companies:c,selectedCompanyId:c[0].companyId,filters:{companyType:"ALL",sector:"ALL",watchlistedOnly:false},savedViews:[{id:"VIEW-ALL-COMPANIES",name:"All Companies"},{id:"VIEW-AM-TENANTS",name:"Advanced Manufacturing Tenants"},{id:"VIEW-COMPANY-WATCHLIST",name:"Company Watchlist"}],map:{synchronized:true,selectedMarkerId:c[0].companyId,visibleMarkerCount:c.length},crossNavigation:{propertyExplorerAvailable:true,knowledgeGraphAvailable:true,gisAvailable:true},liveRefresh:{status:"CONNECTED",revision:5}};}
  function filter(state,filters){state=clone_(state);state.filters=Object.assign({},state.filters,filters||{});var rows=state.companies.filter(function(c){return (state.filters.companyType==="ALL"||c.companyType===state.filters.companyType)&&(state.filters.sector==="ALL"||c.sector===state.filters.sector)&&(!state.filters.watchlistedOnly||c.watchlisted);});state.map.visibleMarkerCount=rows.length;return {state:state,rows:rows};}
  function select(state,id){state=clone_(state);var c=state.companies.filter(function(x){return x.companyId===id;})[0];if(!c)throw new Error("Unknown company");state.selectedCompanyId=id;state.map.selectedMarkerId=id;return {state:state,company:c,profile:{name:c.name,companyType:c.companyType,sector:c.sector,naics:c.naics,sic:c.sic,headquarters:c.headquarters},executives:{count:c.executives.length,people:clone_(c.executives)},facilities:clone_(c.facilityRequirements),propertyRelationships:{count:c.properties.length,properties:clone_(c.properties),status:"SYNCHRONIZED"},relationshipGraph:{nodes:1+c.executives.length+c.properties.length,edges:c.executives.length+c.properties.length,status:"SYNCHRONIZED"},timeline:{events:c.timelineEvents,permanentHistory:true},documents:{linked:c.documents},gisFootprint:{mappedProperties:c.properties.length,status:"SYNCHRONIZED"}};}
  function toggleWatchlist(state,id){state=clone_(state);var found=false;state.companies.forEach(function(c){if(c.companyId===id){c.watchlisted=!c.watchlisted;found=true;}});if(!found)throw new Error("Unknown company");return state;}
  function saveView(state,name,filters){state=clone_(state);state.savedViews.push({id:"VIEW-COMPANY-"+(state.savedViews.length+1),name:name,filters:filters||{}});return state;}
  function crossNavigate(companyId,target,propertyId){var allowed=["PROPERTY_EXPLORER","GIS","KNOWLEDGE_GRAPH","BEGIN_ANALYSIS"];if(allowed.indexOf(target)<0)throw new Error("Unsupported target");return {companyId:companyId,propertyId:propertyId||null,target:target,status:"AVAILABLE",contextPreserved:true,destructive:false,approvalRequired:target==="BEGIN_ANALYSIS"};}
  function certify(){var failures=[],s=createState(),f=filter(s,{companyType:"TENANT"}),x=select(s,"COMP-ABL-SPACE"),w=toggleWatchlist(s,"COMP-AEROJET-ROCKETDYNE"),v=saveView(s,"High Power Aerospace",{sector:"AEROSPACE",minPowerAmps:4000}),n=crossNavigate(x.company.companyId,"PROPERTY_EXPLORER",x.company.properties[0].propertyId);function t(name,condition){if(!condition)failures.push(name);}t("Workspace",s.workspace==="company-explorer");t("Directory",s.companies.length===3);t("Filtering",f.rows.length===2);t("Selection",x.state.selectedCompanyId==="COMP-ABL-SPACE");t("Classification",x.profile.naics==="336414");t("Executives",x.executives.count===2);t("FacilityRequirements",x.facilities.minPowerAmps===4000);t("PropertyRelationships",x.propertyRelationships.count===2);t("RelationshipGraph",x.relationshipGraph.edges===4);t("Timeline",x.timeline.permanentHistory===true);t("Documents",x.documents.linked===3);t("GISFootprint",x.gisFootprint.mappedProperties===2);t("Watchlist",w.companies[1].watchlisted===true);t("SavedViews",v.savedViews.length===4);t("CrossNavigation",n.contextPreserved===true);t("LiveRefresh",s.liveRefresh.status==="CONNECTED");t("Governance",n.destructive===false);t("ContextContinuity",x.state.map.selectedMarkerId===x.company.companyId);return {framework:"SCIIP_V8_SPRINT6_COMPANY_EXPLORER_WORKSPACE",version:"v8.0-sprint6.0",status:failures.length?"FAILED":"PASSED",testsRun:18,failures:failures,result:{workspace:s.workspace,applicationStatus:s.applicationStatus,companiesLoaded:s.companies.length,tenantCompanies:f.rows.length,selectedCompany:x.company.companyId,mapSynchronized:true,savedViews:v.savedViews.length,watchlistedCompanies:w.companies.filter(function(c){return c.watchlisted;}).length,executivesLoaded:x.executives.count,linkedProperties:x.propertyRelationships.count,relationshipNodes:x.relationshipGraph.nodes,relationshipEdges:x.relationshipGraph.edges,timelineEvents:x.timeline.events,linkedDocuments:x.documents.linked,mappedFacilities:x.gisFootprint.mappedProperties,liveRefreshStatus:s.liveRefresh.status,crossNavigationAvailable:true,contextContinuity:true,destructiveActionsEnabledByDefault:false}};}
  return {createState:createState,filter:filter,select:select,toggleWatchlist:toggleWatchlist,saveView:saveView,crossNavigate:crossNavigate,certify:certify};
})();
function sciipV8CompanyExplorerGetState(){return SCIIP_V8_COMPANY_EXPLORER.createState();}
function sciipV8CompanyExplorerSelectCompany(state,companyId){return SCIIP_V8_COMPANY_EXPLORER.select(state,companyId);}
function sciipTestV8Sprint6CompanyExplorerWorkspace(){var result=SCIIP_V8_COMPANY_EXPLORER.certify();console.log(JSON.stringify(result));return result;}
