import React,{useMemo,useState}from'react';
import{CheckCircle2,ChevronRight,ClipboardCheck,Clock3,FileCheck2,PlayCircle,ShieldCheck,TriangleAlert,Workflow}from'lucide-react';
import{actionCenterSnapshot,orchestrateOpportunity,performTaskUpdate,performTransition}from'../workflow/actionCenterService.js';
const opportunityFor=assignment=>({assignmentId:assignment.id,opportunityId:`OPP-${assignment.id}`,title:`${assignment.name} broker execution plan`,priority:'HIGH',owner:'Spencer Casement',evidenceRefs:[`ASSIGNMENT:${assignment.id}`],tasks:[{title:'Review opportunity evidence',kind:'REVIEW'},{title:'Confirm broker strategy',kind:'DECISION'},{title:'Prepare outreach draft',kind:'DRAFT'},{title:'Approve external outreach',kind:'APPROVAL',requiresApproval:true}]});
function Metric({label,value}){return <div className="action-metric"><strong>{value}</strong><span>{label}</span></div>}
function Status({value}){return <span className={`workflow-status ${String(value).toLowerCase().replaceAll('_','-')}`}>{String(value).replaceAll('_',' ')}</span>}
export default function BrokerActionCenter({assignment}){
 const[revision,setRevision]=useState(0);const snapshot=useMemo(()=>actionCenterSnapshot(assignment.id),[assignment.id,revision]);const selected=snapshot.workflows[0]||null;
 const refresh=()=>setRevision(value=>value+1);
 const create=()=>{orchestrateOpportunity(opportunityFor(assignment));refresh()};
 const transition=status=>{performTransition(selected.id,status,status==='APPROVED'?{approvedBy:'Spencer Casement'}:{actor:'Spencer Casement'});refresh()};
 const taskDone=task=>{performTaskUpdate(selected.id,task.id,{status:'COMPLETED'},{actor:'Spencer Casement'});refresh()};
 return <div className="action-center"><section className="action-hero"><div><span className="eyebrow"><Workflow size={14}/> Governed execution</span><h2>Broker Action Center</h2><p>Convert approved intelligence into controlled tasks, decisions, and permanent action history.</p></div><button className="primary-action" onClick={create}>{selected?'Refresh workflow':'Create execution plan'}<ChevronRight size={16}/></button></section>
 <section className="action-metrics"><Metric label="Total workflows" value={snapshot.counts.total}/><Metric label="Pending approval" value={snapshot.counts.pendingApproval}/><Metric label="In progress" value={snapshot.counts.inProgress}/><Metric label="Completed" value={snapshot.counts.completed}/></section>
 {!selected?<section className="action-empty"><ClipboardCheck size={32}/><h3>No governed workflow yet</h3><p>Create a deterministic execution plan for this assignment. No outreach will occur without broker approval.</p><button onClick={create}>Create workflow</button></section>:
 <div className="action-layout"><section className="workflow-card"><header><div><small>{selected.id}</small><h3>{selected.title}</h3><p>{selected.workflowType} · {selected.owner}</p></div><Status value={selected.status}/></header><div className="governance-callout"><ShieldCheck size={18}/><div><strong>Broker control preserved</strong><span>External outreach is blocked until an approval task is completed and the workflow is approved.</span></div></div><div className="workflow-controls">{selected.status==='DRAFT'&&<button onClick={()=>transition('PENDING_APPROVAL')}><FileCheck2 size={15}/>Submit for approval</button>}{selected.status==='PENDING_APPROVAL'&&<button onClick={()=>transition('APPROVED')}><ShieldCheck size={15}/>Approve workflow</button>}{selected.status==='APPROVED'&&<button onClick={()=>transition('IN_PROGRESS')}><PlayCircle size={15}/>Start execution</button>}{selected.status==='IN_PROGRESS'&&selected.tasks.every(t=>t.status==='COMPLETED')&&<button onClick={()=>transition('COMPLETED')}><CheckCircle2 size={15}/>Complete workflow</button>}</div><div className="task-list">{selected.tasks.map(task=><div className="task-row" key={task.id}><button className={`task-check ${task.status==='COMPLETED'?'done':''}`} disabled={task.status==='COMPLETED'} onClick={()=>taskDone(task)}>{task.status==='COMPLETED'?<CheckCircle2 size={18}/>:<Clock3 size={18}/>}</button><div><strong>{task.title}</strong><span>{task.kind} · {task.assignee}</span></div>{task.requiresApproval&&<span className="approval-chip">Approval gate</span>}</div>)}</div></section><aside className="action-history"><h3>Permanent action history</h3><p>Append-only events for this assignment.</p>{snapshot.history.length?snapshot.history.slice().reverse().map(event=><div className="history-event" key={event.id}><span/><div><strong>{event.type.replaceAll('_',' ')}</strong><small>{new Date(event.occurredAt).toLocaleString()}</small></div></div>):<div className="history-empty"><TriangleAlert size={18}/>No action events</div>}</aside></div>}
 </div>
}
