import React,{useMemo,useRef,useState}from'react';
import{AlertTriangle,CalendarDays,CheckCircle2,Clock3,FileCheck2,FileUp,Hash,History,Layers3,ShieldCheck,Trash2}from'lucide-react';
import{inspectPdf}from'../production-validation/documentIdentity.js';
import{clearDocumentRegistry,readDocumentRegistry,registerDocument}from'../production-validation/documentRegistry.js';
import{certifyDocument,summarizeCertifications}from'../production-validation/certificationEngine.js';
import{clearExtractions,importCertifiedExtraction,readExtractions}from'../production-validation/extractionRegistry.js';

const prettyBytes=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
export default function ProductionDataCertificationCenter(){
 const input=useRef(null);const extractionInput=useRef(null);const[extractions,setExtractions]=useState(()=>readExtractions());const[drag,setDrag]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[registry,setRegistry]=useState(()=>readDocumentRegistry());
 const certified=useMemo(()=>registry.map(d=>d.certification?d:certifyDocument(d)),[registry]);const summary=useMemo(()=>summarizeCertifications(certified),[certified]);
 const ingest=async fileList=>{const files=[...fileList].filter(Boolean);if(!files.length)return;setBusy(true);setMessage('');let next=registry,added=0,duplicates=0,failed=0;
  for(const file of files){try{const inspected=await inspectPdf(file);const document=certifyDocument(inspected);const result=registerDocument(document);next=result.registry;if(result.duplicate)duplicates++;else added++;}catch(error){failed++;setMessage(error.message)}}
  setRegistry(next);setBusy(false);if(!failed)setMessage(`${added} PDF${added===1?'':'s'} registered${duplicates?`; ${duplicates} exact duplicate${duplicates===1?'':'s'} blocked`:''}.`)};
 const importExtraction=async file=>{if(!file)return;try{const payload=JSON.parse(await file.text());const result=importCertifiedExtraction(payload);setExtractions(result.registry);setMessage(`${result.added} certified extraction${result.added===1?'':'s'} imported${result.duplicates?`; ${result.duplicates} duplicate${result.duplicates===1?'':'s'} blocked`:''}.`)}catch(error){setMessage(error.message)}};
 const extractionSummary=useMemo(()=>({documents:extractions.length,observations:extractions.reduce((n,x)=>n+(x.observations?.length||0),0),review:extractions.reduce((n,x)=>n+(x.summary?.reviewRequired||0),0)}),[extractions]);
 const reset=()=>{if(confirm('Clear the local PDF certification and extraction registries for this browser?')){setRegistry(clearDocumentRegistry());setExtractions(clearExtractions())}};
 return <div className="production-validation-workspace"><section className="pv-main"><div className="pv-heading"><div><span className="pv-kicker">RELEASE 5.5 · PRODUCTION VALIDATION</span><h2>Daily SuperSheet Certification</h2><p>Register each AIR CRE PDF as immutable market evidence before extraction, temporal resolution, graph projection, or AI use.</p></div><span className="pv-health"><ShieldCheck size={17}/>Governed intake active</span></div>
 <div className={`pv-dropbox ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);ingest(e.dataTransfer.files)}}><FileUp size={34}/><h3>Drop today’s SuperSheet PDF here</h3><p>The drop box remains permanently available for daily uploads. Multiple historical PDFs may also be added together.</p><button disabled={busy} onClick={()=>input.current?.click()}>{busy?'Registering…':'Choose PDF files'}</button><input ref={input} hidden multiple type="file" accept="application/pdf,.pdf" onChange={e=>ingest(e.target.files)}/><small>PDF only · SHA-256 duplicate protection · source files are never overwritten</small></div><div className="pv-extraction-import"><div><ShieldCheck size={20}/><div><strong>Import certified AIR CRE extraction</strong><span>Run the local connector against the daily PDF folder, then import its governed JSON output.</span></div></div><button className="pv-secondary" onClick={()=>extractionInput.current?.click()}>Import extraction JSON</button><input ref={extractionInput} hidden type="file" accept="application/json,.json" onChange={e=>importExtraction(e.target.files[0])}/></div>
 {message&&<div className="pv-message"><CheckCircle2 size={16}/>{message}</div>}
 <div className="pv-extraction-banner"><strong>{extractionSummary.observations.toLocaleString()} certified observations</strong><span>{extractionSummary.documents} documents · {extractionSummary.review} records gated for review · no silent promotion</span></div><div className="pv-metrics">{[[FileCheck2,'Documents',summary.documents],[ShieldCheck,'Certified',summary.CERTIFIED],[Clock3,'Staged',summary.STAGED],[AlertTriangle,'Review',summary.REVIEW_REQUIRED],[Layers3,'Average score',`${summary.averageScore}%`],[CalendarDays,'Latest report',summary.latestReportDate||'—']].map(([Icon,label,value])=><div key={label}><Icon size={18}/><span>{label}</span><strong>{value}</strong></div>)}</div>
 <section className="pv-registry"><header><div><h3>Immutable document registry</h3><p>Every entry retains the report date, fingerprint, page estimate, file size, and certification gates.</p></div><button className="pv-secondary" onClick={reset} disabled={!registry.length}><Trash2 size={15}/>Clear local registry</button></header>
 <div className="pv-table"><table><thead><tr><th>Status</th><th>Report date</th><th>Source PDF</th><th>Pages</th><th>Size</th><th>Fingerprint</th><th>Next gate</th></tr></thead><tbody>{certified.length?certified.map(d=><tr key={d.documentId}><td><span className={`pv-status ${d.certification.status.toLowerCase()}`}>{d.certification.status.replaceAll('_',' ')}</span></td><td>{d.reportDate||'Needs review'}</td><td><strong>{d.fileName}</strong><small>{d.documentId}</small></td><td>{d.pageCount}</td><td>{prettyBytes(d.fileSize)}</td><td><code>{d.fingerprint.slice(0,12)}…</code></td><td>Page extraction pending</td></tr>):<tr><td colSpan="7"><div className="pv-empty"><History size={22}/><strong>No PDFs registered yet</strong><span>Use the drop box above for today’s SuperSheet.</span></div></td></tr>}</tbody></table></div></section></section>
 <aside className="pv-side"><section><Hash size={19}/><h3>Evidence identity</h3><p>Each PDF receives a deterministic document ID and SHA-256 fingerprint. Exact duplicates are blocked without deleting history.</p></section><section><Layers3 size={19}/><h3>Progressive certification</h3><ol><li className="done">Discovered</li><li className="done">Identity certified</li><li>Page extraction</li><li>Temporal resolution</li><li>Graph projection</li><li>AI evidence ready</li></ol></section><section><ShieldCheck size={19}/><h3>Governance boundary</h3><p>Registration does not promote extracted facts. Page-level evidence, confidence, and human-review gates must pass first.</p></section></aside></div>;
}