import React,{useMemo,useRef,useState}from'react';
import{AlertTriangle,CheckCircle2,FileSpreadsheet,History,ShieldCheck,UploadCloud,XCircle}from'lucide-react';
import{parseSuperSheet}from'../ingestion/superSheetParser.js';
import{mapHeaders,validateRequiredHeaders}from'../ingestion/schemaRegistry.js';
import{normalizeBatch}from'../ingestion/normalizer.js';
import{appendLedger,createIngestionId,readLedger}from'../ingestion/ingestionLedger.js';
import{projectRowsToGraph}from'../knowledge/graphProjection.js';
import{promoteProjection}from'../knowledge/graphStore.js';

const tone=status=>status==='ACCEPTED'?'accepted':status==='WARNING'?'warning':'rejected';
export default function SuperSheetIngestion({assignment}){
 const input=useRef(null);const[drag,setDrag]=useState(false);const[parsed,setParsed]=useState(null);const[results,setResults]=useState([]);const[error,setError]=useState('');const[promoted,setPromoted]=useState(false);const[ledger,setLedger]=useState(()=>readLedger());
 const mapping=useMemo(()=>parsed?mapHeaders(parsed.headers):null,[parsed]);const required=useMemo(()=>mapping?validateRequiredHeaders(mapping):null,[mapping]);
 const summary=useMemo(()=>results.reduce((a,row)=>(a[row.status]=(a[row.status]||0)+1,a),{ACCEPTED:0,WARNING:0,REJECTED:0}),[results]);
 const load=async file=>{if(!file)return;setError('');setPromoted(false);try{const next=await parseSuperSheet(file);const nextMap=mapHeaders(next.headers);const valid=validateRequiredHeaders(nextMap);setParsed(next);setResults(valid.valid?normalizeBatch(next.rows,nextMap):[]);if(!valid.valid)setError(`Missing required column: ${valid.missing.join(', ')}`);}catch(e){setParsed(null);setResults([]);setError(e.message)}};
 const promote=()=>{const accepted=results.filter(row=>row.status!=='REJECTED').map(row=>row.normalized);const ingestionId=createIngestionId(parsed.fileName,accepted);const entry={ingestionId,assignmentId:assignment.id,fileName:parsed.fileName,format:parsed.format,createdAt:new Date().toISOString(),accepted:summary.ACCEPTED,warnings:summary.WARNING,rejected:summary.REJECTED,rows:accepted.length};const saved=appendLedger(entry);setLedger(saved.ledger);setPromoted(true);if(saved.duplicate){setError('Duplicate-safe guard: this exact batch already exists in the ingestion ledger.');return;}const projection=projectRowsToGraph(accepted,{assignmentId:assignment.id,assignmentName:assignment.name,ingestionId,fileName:parsed.fileName});promoteProjection(projection);};
 return <div className="ingestion-workspace"><section className="ingestion-main"><div className={`upload-zone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);load(e.dataTransfer.files[0])}}><UploadCloud size={30}/><h2>Upload governed SuperSheet</h2><p>Drag and drop an XLSX, CSV, TSV, or JSON file. Daily PDF SuperSheets belong in Production Data Certification. SCIIP validates and normalizes every row before promotion.</p><button onClick={()=>input.current?.click()}>Choose file</button><input ref={input} type="file" accept=".xlsx,.csv,.tsv,.json" hidden onChange={e=>load(e.target.files[0])}/></div>{error&&<div className="ingestion-error"><AlertTriangle size={16}/>{error}</div>}{parsed&&<><div className="ingestion-summary"><div><FileSpreadsheet/><span>File</span><strong>{parsed.fileName}</strong></div><div><ShieldCheck/><span>Schema coverage</span><strong>{Math.round(mapping.coverage*100)}%</strong></div><div><CheckCircle2/><span>Accepted</span><strong>{summary.ACCEPTED}</strong></div><div><AlertTriangle/><span>Warnings</span><strong>{summary.WARNING}</strong></div><div><XCircle/><span>Rejected</span><strong>{summary.REJECTED}</strong></div></div><section className="ingestion-table-card"><header><div><h3>Validation preview</h3><p>{results.length} source rows evaluated against the canonical property schema</p></div><button disabled={!required?.valid||!results.some(row=>row.status!=='REJECTED')} onClick={promote}>{promoted?'Promoted':'Promote accepted rows'}</button></header><div className="ingestion-table"><table><thead><tr><th>Status</th><th>Source row</th><th>Address</th><th>City</th><th>Building SF</th><th>Issues</th></tr></thead><tbody>{results.slice(0,250).map((row,index)=><tr key={index}><td><span className={`row-status ${tone(row.status)}`}>{row.status}</span></td><td>{row.normalized.sourceRow}</td><td>{row.normalized.address||'—'}</td><td>{row.normalized.city||'—'}</td><td>{row.normalized.buildingSf?.toLocaleString()||'—'}</td><td>{[...row.errors,...row.warnings].join('; ')||'Ready'}</td></tr>)}</tbody></table></div></section></>}</section><aside className="ingestion-side"><section><header><History size={16}/><div><h3>Ingestion ledger</h3><p>Permanent, duplicate-safe local history</p></div></header>{ledger.length?ledger.slice(0,8).map(item=><div className="ledger-entry" key={item.ingestionId}><strong>{item.fileName}</strong><span>{item.rows} promoted rows · {new Date(item.createdAt).toLocaleString()}</span><code>{item.ingestionId}</code></div>):<p className="ledger-empty">No governed batches have been promoted in this browser.</p>}</section><section className="governance-card"><ShieldCheck size={20}/><h3>Promotion control</h3><p>Rejected rows never promote. Warnings remain visible. Exact batches are blocked from duplicate promotion. Promoted rows project automatically into the governed property knowledge graph.</p></section></aside></div>
}
