/** SCIIP_OS v7.0 — Epic 4 Sprint 1: Shared Context and Evidence Gateway */
var SCIIP_UNIFIED_PLATFORM_CONTEXT_EVIDENCE_SERVICE=(function(){
  'use strict';
  function text(v){return v===null||v===undefined?'':String(v).trim();}
  function upper(v){return text(v).toUpperCase();}
  function normalizeContext(c){c=c||{};return {workspace:upper(c.workspace||'UNKNOWN'),selectedEntityId:text(c.selectedEntityId),entityIds:(c.entityIds||[]).map(text).filter(Boolean),marketIds:(c.marketIds||[]).map(text).filter(Boolean),geometryIds:(c.geometryIds||[]).map(text).filter(Boolean),opportunityIds:(c.opportunityIds||[]).map(text).filter(Boolean),workflowIds:(c.workflowIds||[]).map(text).filter(Boolean),evidenceIds:(c.evidenceIds||[]).map(text).filter(Boolean),actorId:text(c.actorId||'SYSTEM'),readOnly:!!c.readOnly,reviewRequired:c.reviewRequired!==false,destructiveCommitEnabled:false,autonomousExecution:false};}
  function propagate(source,targetWorkspace,additions){var out=normalizeContext(source),a=normalizeContext(additions||{});out.workspace=upper(targetWorkspace||out.workspace);['entityIds','marketIds','geometryIds','opportunityIds','workflowIds','evidenceIds'].forEach(function(k){out[k]=out[k].concat(a[k]).filter(function(v,i,x){return x.indexOf(v)===i;});});if(a.selectedEntityId)out.selectedEntityId=a.selectedEntityId;if(a.actorId&&a.actorId!=='SYSTEM')out.actorId=a.actorId;out.readOnly=out.readOnly||a.readOnly;return out;}
  function validateEvidence(evidence,policy){policy=policy||{};var min=Number(policy.minimumConfidence||60),rows=(evidence||[]).map(function(e){return {evidenceId:text(e.evidenceId),sourceType:upper(e.sourceType||'UNKNOWN'),sourceId:text(e.sourceId),confidence:Math.max(0,Math.min(100,Number(e.confidence||0))),observedAt:text(e.observedAt),immutable:e.immutable!==false};}),failures=[];rows.forEach(function(e){if(!e.evidenceId)failures.push('EVIDENCE_ID_REQUIRED');if(!e.sourceId)failures.push('SOURCE_ID_REQUIRED');if(e.confidence<min)failures.push('CONFIDENCE_BELOW_POLICY:'+e.evidenceId);if(!e.immutable)failures.push('IMMUTABLE_EVIDENCE_REQUIRED:'+e.evidenceId);});return {status:failures.length?'REVIEW_REQUIRED':'VALID',evidence:rows,failures:failures,minimumConfidence:min,reviewRequired:true};}
  function lineage(context,evidence){var c=normalizeContext(context),v=validateEvidence(evidence||[],{minimumConfidence:0});return {workspace:c.workspace,entityIds:c.entityIds,evidenceIds:v.evidence.map(function(e){return e.evidenceId;}),sources:v.evidence.map(function(e){return {evidenceId:e.evidenceId,sourceType:e.sourceType,sourceId:e.sourceId};}),traceable:v.failures.length===0,reviewRequired:true,appendOnly:true};}
  return {normalizeContext:normalizeContext,propagate:propagate,validateEvidence:validateEvidence,lineage:lineage};
}());
