var SCIIP_S31_APPLICATION=(function(){'use strict';var VERSION='v7.0-integration-sprint-31.0';
function definition(){return {id:'enterprise-digital-coo',name:'Enterprise Digital COO',version:VERSION,dependencies:['enterprise-digital-ceo','enterprise-autonomous-execution-work-management'],services:['enterprise-digital-coo'],queries:['enterprise-digital-coo-query'],events:['EXECUTIVE_RECOMMENDATION_CREATED','EXECUTIVE_APPROVAL_ROUTED','EXECUTIVE_COMMAND_ISSUED'],stateBindings:['executiveSuite','enterprise_digital_coo'],workspaces:['enterprise-digital-coo'],tests:['sciipTestV7IntegrationSprint31'],liveHandler:'sciipEnterpriseDigitalCooHeartbeatV7',queryHandler:'sciipEnterpriseDigitalCooQueryV7'};}
function run(r){r=r||{};var synthesis=SCIIP_S31_OPERATIONS_SYNTHESIS_ENGINE.analyze(r),optimization=SCIIP_S31_OPERATIONS_OPTIMIZATION_ENGINE.optimize({synthesis:synthesis}),resilience=SCIIP_S31_OPERATIONAL_RESILIENCE_ENGINE.assess(r),scorecard=SCIIP_S31_COO_SCORECARD.calculate({synthesis:synthesis,optimization:optimization,resilience:resilience}),workspace=SCIIP_S31_EXECUTIVE_COO_WORKSPACE.build({synthesis:synthesis,optimization:optimization,resilience:resilience,scorecard:scorecard});return {version:VERSION,status:'AVAILABLE',synthesis:synthesis,optimization:optimization,resilience:resilience,scorecard:scorecard,workspace:workspace};}
function names(s,ks){var raw=[];for(var i=0;i<ks.length;i++)if(s&&s[ks[i]]!=null){raw=s[ks[i]];break;}if(Array.isArray(raw))return raw.map(function(x){return typeof x==='string'?x:String((x&&(x.name||x.id))||'');});return raw&&typeof raw==='object'?Object.keys(raw):[];}
function wire(){var o={status:'PARTIAL',registry:false,assembly:false,queryRegistered:false,liveServiceRegistered:false,sharedState:typeof SCIIP_APP_STATE!=='undefined',eventBus:typeof SCIIP_APP_EVENTS!=='undefined',registrationMode:[]};try{o.registry=SCIIP_PLATFORM_REGISTRY.register(definition()).status!=='CONFLICT';}catch(e){}try{o.assembly=SCIIP_PLATFORM_SELF_ASSEMBLY.assemble({source:'SPRINT_31'}).status!=='FAILED';if(o.assembly)o.registrationMode.push('SELF_ASSEMBLY');}catch(e2){}var qs=typeof SCIIP_QUERY_ENGINE!=='undefined'&&SCIIP_QUERY_ENGINE.snapshot?SCIIP_QUERY_ENGINE.snapshot():{},ls=typeof SCIIP_LIVE_RUNTIME!=='undefined'&&SCIIP_LIVE_RUNTIME.snapshot?SCIIP_LIVE_RUNTIME.snapshot():{};o.queryRegistered=names(qs,['registeredQueries','queries','registry']).indexOf('enterprise-digital-coo-query')!==-1;o.liveServiceRegistered=names(ls,['services','registry']).indexOf('enterprise-digital-coo')!==-1;if(!o.queryRegistered&&typeof SCIIP_QUERY_ENGINE!=='undefined'&&SCIIP_QUERY_ENGINE.register){SCIIP_QUERY_ENGINE.register('enterprise-digital-coo-query',sciipEnterpriseDigitalCooQueryV7,{capability:definition().id});o.queryRegistered=true;}if(!o.liveServiceRegistered&&typeof SCIIP_LIVE_RUNTIME!=='undefined'&&SCIIP_LIVE_RUNTIME.register){SCIIP_LIVE_RUNTIME.register('enterprise-digital-coo',sciipEnterpriseDigitalCooHeartbeatV7,{capability:definition().id});o.liveServiceRegistered=true;}if(o.registry&&o.assembly&&o.queryRegistered&&o.liveServiceRegistered&&o.sharedState&&o.eventBus)o.status='WIRED';return o;}
return {VERSION:VERSION,run:run,wire:wire,platformDefinition:definition};})();
function sciipEnterpriseDigitalCooQueryV7(r){return SCIIP_S31_APPLICATION.run(r||{});}function sciipEnterpriseDigitalCooHeartbeatV7(){return {status:'AVAILABLE',version:'v7.0-integration-sprint-31.0',workspace:'enterprise-digital-coo',generatedAt:new Date().toISOString()};}

var SCIIP_S31_APPLICATION=SCIIP_S31_APPLICATION;
