function sciipBuildV7Epic4ExecutionRuntimeMilestone(){
  var bus=SCIIP_ENTERPRISE_EVENT_BUS.create(),received=[];bus.subscribe('opportunity.created',function(e){received.push(e.eventId);});bus.publish('opportunity.created',{id:'OPP-1'},{workspace:'executive'});bus.publish('opportunity.created',{id:'OPP-2'},{workspace:'gis'});
  var broker=SCIIP_RELIABLE_MESSAGE_BROKER.create({maxAttempts:1});broker.enqueue('execution',{id:'TASK-1'});broker.consume('execution',function(m){return {processed:m.payload.id};});broker.enqueue('execution',{id:'TASK-FAIL'});broker.consume('execution',function(){throw new Error('EXPECTED_FAILURE');});
  var workflow=SCIIP_WORKFLOW_ORCHESTRATION_RUNTIME.create();var completed=workflow.execute({id:'WF-1',steps:[{id:'prepare',execute:function(){return 'READY';}},{id:'execute',requiresApproval:true,execute:function(){return 'DONE';}}]},{approved:true});var blocked=workflow.execute({id:'WF-2',steps:[{id:'approve',requiresApproval:true,execute:function(){return 'DONE';}}]},{approved:false});
  var scheduler=SCIIP_GOVERNED_SCHEDULER.create();scheduler.register({id:'JOB-1',reviewRequired:true,execute:function(){return {status:'RAN'};}});scheduler.run('JOB-1',{approved:true});
  var replay=SCIIP_EVENT_REPLAY_RECOVERY_SERVICE.create(),replayed=[];var replayResult=replay.replay('opportunities',bus.history('opportunity.created'),function(e){replayed.push(e.eventId);},{fromSequence:1});
  var recovery=SCIIP_DEAD_LETTER_RECOVERY_SERVICE.create(broker);var recoveryResult=recovery.recover('execution',function(msg){return msg.payload.id==='TASK-FAIL';});
  var persistence=SCIIP_EXECUTION_AUDIT_PERSISTENCE.create();persistence.append({businessKey:'EXECUTION-RUNTIME|CERTIFICATION|1',status:'CERTIFIED'});persistence.append({businessKey:'EXECUTION-RUNTIME|CERTIFICATION|1',status:'CERTIFIED'});
  var acks=broker.acknowledgements();var health=SCIIP_EXECUTION_RUNTIME_HEALTH_CERTIFICATION.certify({events:bus.history().length,acknowledged:acks.filter(function(x){return x.status==='ACKNOWLEDGED';}).length,deadLettered:acks.filter(function(x){return x.status==='DEAD_LETTERED';}).length,workflowCompleted:completed.status==='COMPLETED',approvalBlocked:blocked.status==='WAITING_FOR_APPROVAL',scheduledRuns:scheduler.history().length,replayed:replayResult.eventsReplayed,persisted:persistence.count(),northStarAligned:true});
  return {bus:bus,received:received,broker:broker,workflow:workflow,completed:completed,blocked:blocked,scheduler:scheduler,replay:replay,replayResult:replayResult,recovery:recovery,recoveryResult:recoveryResult,persistence:persistence,health:health};
}
