/** SCIIP_OS v7.0 — Epic 6 Sprint 8: Executive Leasing, Tenant Pipeline & Revenue Operations */
var SCIIP_EPIC6_LEASING_REVENUE = (function () {
  var VERSION='v7.0-epic6-sprint8.0';
  var FRAMEWORK='SCIIP_V7_EPIC6_SPRINT8_EXECUTIVE_LEASING_TENANT_PIPELINE_REVENUE_OPERATIONS';
  var state_={pipelines:[],pursuits:[],forecasts:[],accountability:[],alerts:[],actions:[],executions:[],audit:[]};
  function now_(){return new Date().toISOString();}
  function id_(p){var r=(typeof Utilities!=='undefined'&&Utilities.getUuid)?Utilities.getUuid():String(Date.now())+String(Math.random());return p+'-'+String(r).replace(/[^a-zA-Z0-9]/g,'').slice(0,12);}
  function copy_(v){return JSON.parse(JSON.stringify(v));}
  function num_(v,d){var n=Number(v);return isFinite(n)?n:d;}
  function clamp_(v,min,max){return Math.max(min,Math.min(max,v));}
  function audit_(type,id,payload){state_.audit.push({auditId:id_('AUDIT'),type:type,entityId:id,payload:copy_(payload||{}),occurredAt:now_(),permanent:true});}
  function score_(t){
    var credit=clamp_(num_(t.creditScore,50),0,100), fit=clamp_(num_(t.propertyFit,50),0,100), velocity=clamp_(num_(t.dealVelocity,50),0,100), probability=clamp_(num_(t.probability,25),0,100), sf=Math.max(0,num_(t.requirementSf,0));
    return Math.round((credit*.30+fit*.30+velocity*.20+probability*.15+Math.min(100,sf/5000)*.05)*100)/100;
  }
  function createPipeline(request){
    request=request||{};var tenants=request.tenants||[];if(!request.propertyId)throw new Error('propertyId required');if(!tenants.length)throw new Error('At least one tenant pursuit is required.');
    var pipelineId=id_('LEASEPIPE');var pursuits=tenants.map(function(t,i){if(!t.tenantId)throw new Error('tenantId required at index '+i);var p={pursuitId:id_('PURSUIT'),pipelineId:pipelineId,propertyId:request.propertyId,tenantId:t.tenantId,tenantName:t.tenantName||t.tenantId,requirementSf:num_(t.requirementSf,0),askingRent:num_(t.askingRent,0),targetRent:num_(t.targetRent,0),termMonths:num_(t.termMonths,60),stage:String(t.stage||'PROSPECT').toUpperCase(),probability:clamp_(num_(t.probability,20),0,100),creditScore:num_(t.creditScore,50),propertyFit:num_(t.propertyFit,50),dealVelocity:num_(t.dealVelocity,50),priorityScore:0,broker:t.broker||'Unassigned',nextAction:t.nextAction||'',dueDate:t.dueDate||'',evidence:copy_(t.evidence||[]),lineage:copy_(t.lineage||{source:'leasing-pipeline'})};p.priorityScore=score_(p);return p;});
    pursuits.sort(function(a,b){return b.priorityScore-a.priorityScore;});
    var pipe={pipelineId:pipelineId,propertyId:request.propertyId,address:request.address||'',status:'ACTIVE',pursuits:pursuits,createdAt:now_(),reviewRequired:true,lineagePreserved:true};state_.pipelines.push(pipe);state_.pursuits=state_.pursuits.concat(pursuits);audit_('LEASING_PIPELINE_CREATED',pipelineId,{propertyId:request.propertyId,pursuits:pursuits.length});return copy_(pipe);
  }
  function advancePursuit(pursuitId,stage,options){options=options||{};var p=state_.pursuits.filter(function(x){return x.pursuitId===pursuitId;})[0];if(!p)throw new Error('Pursuit not found: '+pursuitId);p.stage=String(stage||'').toUpperCase();p.probability=clamp_(num_(options.probability,p.probability),0,100);p.nextAction=options.nextAction||p.nextAction;p.dueDate=options.dueDate||p.dueDate;p.updatedAt=now_();p.priorityScore=score_(p);audit_('TENANT_PURSUIT_'+p.stage,pursuitId,{probability:p.probability});return copy_(p);}
  function forecastRevenue(pipelineId,request){request=request||{};var pipe=state_.pipelines.filter(function(x){return x.pipelineId===pipelineId;})[0];if(!pipe)throw new Error('Pipeline not found: '+pipelineId);var vacantSf=Math.max(0,num_(request.vacantSf,0));var months=Math.max(1,num_(request.forecastMonths,12));var weightedSf=0,weightedAnnualRevenue=0;pipe.pursuits.forEach(function(p){var w=p.probability/100;weightedSf+=p.requirementSf*w;weightedAnnualRevenue+=p.requirementSf*p.targetRent*12*w;});var absorption=Math.min(vacantSf,weightedSf);var forecast={forecastId:id_('LEASEFCST'),pipelineId:pipelineId,propertyId:pipe.propertyId,forecastMonths:months,vacantSf:vacantSf,weightedAbsorptionSf:Math.round(absorption),projectedOccupancyPct:vacantSf?Math.round((absorption/vacantSf)*10000)/100:100,weightedAnnualRevenue:Math.round(weightedAnnualRevenue),direction:weightedAnnualRevenue>0?'UP':'FLAT',createdAt:now_(),lineagePreserved:true};state_.forecasts.push(forecast);audit_('LEASING_REVENUE_FORECAST_CREATED',forecast.forecastId,{pipelineId:pipelineId});return copy_(forecast);}
  function assignBrokerAccountability(request){request=request||{};if(!request.broker)throw new Error('broker required');var a={accountabilityId:id_('BROKERKPI'),broker:request.broker,propertyId:request.propertyId||'',pursuitTarget:num_(request.pursuitTarget,0),tourTarget:num_(request.tourTarget,0),proposalTarget:num_(request.proposalTarget,0),actualPursuits:num_(request.actualPursuits,0),actualTours:num_(request.actualTours,0),actualProposals:num_(request.actualProposals,0),status:'ACTIVE',reviewDate:request.reviewDate||'',createdAt:now_()};a.completionPct=Math.round(((a.pursuitTarget?a.actualPursuits/a.pursuitTarget:1)+(a.tourTarget?a.actualTours/a.tourTarget:1)+(a.proposalTarget?a.actualProposals/a.proposalTarget:1))/3*10000)/100;state_.accountability.push(a);audit_('BROKER_ACCOUNTABILITY_ASSIGNED',a.accountabilityId,{broker:a.broker});return copy_(a);}
  function detectRevenueRisk(pipelineId,request){request=request||{};var pipe=state_.pipelines.filter(function(x){return x.pipelineId===pipelineId;})[0];if(!pipe)throw new Error('Pipeline not found: '+pipelineId);var vacancy=num_(request.vacancyPct,0), rollover=num_(request.rolloverRiskPct,0), downtime=num_(request.expectedDowntimeMonths,0), weighted=pipe.pursuits.reduce(function(s,p){return s+p.probability;},0)/pipe.pursuits.length;var score=Math.round((vacancy*.4+rollover*.35+Math.min(100,downtime*8)*.15+(100-weighted)*.10)*100)/100;var severity=score>=65?'CRITICAL':(score>=40?'WARNING':'WATCH');var alert={alertId:id_('REVRISK'),pipelineId:pipelineId,propertyId:pipe.propertyId,score:score,severity:severity,status:'OPEN',drivers:{vacancyPct:vacancy,rolloverRiskPct:rollover,expectedDowntimeMonths:downtime,averagePursuitProbability:Math.round(weighted*100)/100},createdAt:now_(),reviewRequired:true};state_.alerts.push(alert);audit_('REVENUE_RISK_ALERT_CREATED',alert.alertId,{severity:severity,score:score});return copy_(alert);}
  function createLeasingAction(request){request=request||{};if(!request.propertyId)throw new Error('propertyId required');var a={actionId:id_('LEASEACT'),propertyId:request.propertyId,pursuitId:request.pursuitId||'',type:String(request.type||'BROKER_FOLLOW_UP').toUpperCase(),owner:request.owner||'Leasing Team',status:'OPEN',dueDate:request.dueDate||'',workspace:request.workspace||'executive-operations',notes:request.notes||'',approvalRequired:request.approvalRequired!==false,createdAt:now_(),lineage:copy_(request.lineage||{})};state_.actions.push(a);audit_('LEASING_ACTION_CREATED',a.actionId,{type:a.type});return copy_(a);}
  function approveAction(actionId,decision,options){options=options||{};var a=state_.actions.filter(function(x){return x.actionId===actionId;})[0];if(!a)throw new Error('Action not found: '+actionId);decision=String(decision||'').toUpperCase();if(['APPROVE','REJECT','RETURN'].indexOf(decision)<0)throw new Error('Unsupported decision');a.status=decision==='APPROVE'?'APPROVED':(decision==='REJECT'?'REJECTED':'RETURNED_FOR_REVISION');a.reviewer=options.reviewer||'Executive Committee';a.rationale=options.rationale||'';a.decidedAt=now_();audit_('LEASING_ACTION_'+a.status,actionId,{reviewer:a.reviewer});return copy_(a);}
  function executeAction(actionId,options){options=options||{};var a=state_.actions.filter(function(x){return x.actionId===actionId;})[0];if(!a)throw new Error('Action not found: '+actionId);if(a.approvalRequired&&a.status!=='APPROVED')throw new Error('Action must be APPROVED.');var destructive=!!options.destructive;var certified=!!options.certificationToken&&options.certificationToken===options.expectedCertificationToken;var status=destructive&&!certified?'BLOCKED_GOVERNANCE':(destructive?'CERTIFIED_EXECUTION_READY':'DRY_RUN_COMPLETED');var e={executionId:id_('LEASEEXEC'),actionId:actionId,status:status,receiptId:id_('LEASERECEIPT'),executedAt:now_(),destructive:destructive,tokenValidated:certified,lineagePreserved:true,rollbackAvailable:destructive&&certified};state_.executions.push(e);audit_('LEASING_ACTION_EXECUTION_'+status,actionId,e);return copy_(e);}
  function dashboard(){return {framework:FRAMEWORK,version:VERSION,workspace:'executive-operations',portalStatus:'OPERATIONAL',pipelines:copy_(state_.pipelines),pursuits:copy_(state_.pursuits),forecasts:copy_(state_.forecasts),brokerAccountability:copy_(state_.accountability),revenueRiskAlerts:copy_(state_.alerts),actions:copy_(state_.actions),executions:copy_(state_.executions),auditEvents:copy_(state_.audit),reviewRequired:true,lineagePreserved:true,destructiveLeasingExecutionEnabledByDefault:false};}
  function reset_(){state_={pipelines:[],pursuits:[],forecasts:[],accountability:[],alerts:[],actions:[],executions:[],audit:[]};}
  function certify(){
    reset_();
    var pipe=createPipeline({propertyId:'P-LOWELL',address:'2125 W Lowell St, Rialto',tenants:[
      {tenantId:'T-AERO',tenantName:'Aerospace Systems Co.',requirementSf:300000,targetRent:1.48,stage:'PROPOSAL',probability:70,creditScore:92,propertyFit:96,dealVelocity:82,broker:'Spencer Casement',evidence:['RFP','TOUR_NOTES']},
      {tenantId:'T-LOG',tenantName:'National Logistics User',requirementSf:220000,targetRent:1.42,stage:'TOUR',probability:45,creditScore:88,propertyFit:84,dealVelocity:68,broker:'Leasing Team'},
      {tenantId:'T-MFG',tenantName:'Advanced Manufacturing User',requirementSf:150000,targetRent:1.55,stage:'PROSPECT',probability:25,creditScore:74,propertyFit:90,dealVelocity:55,broker:'Leasing Team'}
    ]});
    var advanced=advancePursuit(pipe.pursuits[0].pursuitId,'LOI',{probability:82,nextAction:'Complete economics review'});
    var forecast=forecastRevenue(pipe.pipelineId,{vacantSf:664859,forecastMonths:12});
    var broker=assignBrokerAccountability({broker:'Spencer Casement',propertyId:'P-LOWELL',pursuitTarget:5,tourTarget:3,proposalTarget:2,actualPursuits:5,actualTours:2,actualProposals:2,reviewDate:'2026-07-31'});
    var alert=detectRevenueRisk(pipe.pipelineId,{vacancyPct:100,rolloverRiskPct:55,expectedDowntimeMonths:12});
    var action=createLeasingAction({propertyId:'P-LOWELL',pursuitId:advanced.pursuitId,type:'ECONOMICS_APPROVAL',owner:'Executive Leasing Committee',dueDate:'2026-07-24'});
    var approved=approveAction(action.actionId,'APPROVE',{reviewer:'Executive Committee',rationale:'Priority pursuit exceeds return threshold.'});
    var dry=executeAction(action.actionId,{destructive:false});
    var blocked=executeAction(action.actionId,{destructive:true,certificationToken:'BAD',expectedCertificationToken:'GOOD'});
    var tests=[pipe.pursuits.length===3,pipe.pursuits[0].tenantId==='T-AERO',advanced.stage==='LOI',forecast.direction==='UP',forecast.weightedAbsorptionSf>0,broker.status==='ACTIVE',alert.severity==='CRITICAL',approved.status==='APPROVED',dry.status==='DRY_RUN_COMPLETED',blocked.status==='BLOCKED_GOVERNANCE'];
    var failures=[];tests.forEach(function(v,i){if(!v)failures.push('test'+(i+1));});
    return {framework:FRAMEWORK,version:VERSION,status:failures.length?'FAILED':'PASSED',testsRun:tests.length,failures:failures,result:{workspace:'executive-operations',portalStatus:'OPERATIONAL',pipelines:1,pursuits:pipe.pursuits.length,topTenant:pipe.pursuits[0].tenantId,topPriorityScore:pipe.pursuits[0].priorityScore,advancedStage:advanced.stage,forecastDirection:forecast.direction,weightedAbsorptionSf:forecast.weightedAbsorptionSf,weightedAnnualRevenue:forecast.weightedAnnualRevenue,brokerAccountability:1,brokerCompletionPct:broker.completionPct,revenueRiskAlerts:1,revenueRiskSeverity:alert.severity,leasingActions:1,approvalStatus:approved.status,executionStatus:dry.status,destructiveExecution:blocked.status,receipts:2,auditEvents:state_.audit.length,reviewRequired:true,lineagePreserved:true,destructiveLeasingExecutionEnabledByDefault:false}};
  }
  return {createPipeline:createPipeline,advancePursuit:advancePursuit,forecastRevenue:forecastRevenue,assignBrokerAccountability:assignBrokerAccountability,detectRevenueRisk:detectRevenueRisk,createLeasingAction:createLeasingAction,approveAction:approveAction,executeAction:executeAction,dashboard:dashboard,certify:certify};
})();
function sciipGetEpic6ExecutiveLeasingTenantPipelineRevenueOperations(){return SCIIP_EPIC6_LEASING_REVENUE.dashboard();}
function sciipCreateEpic6LeasingPipeline(request){return SCIIP_EPIC6_LEASING_REVENUE.createPipeline(request);}
function sciipAdvanceEpic6TenantPursuit(pursuitId,stage,options){return SCIIP_EPIC6_LEASING_REVENUE.advancePursuit(pursuitId,stage,options);}
function sciipForecastEpic6LeasingRevenue(pipelineId,request){return SCIIP_EPIC6_LEASING_REVENUE.forecastRevenue(pipelineId,request);}
function sciipAssignEpic6BrokerAccountability(request){return SCIIP_EPIC6_LEASING_REVENUE.assignBrokerAccountability(request);}
function sciipDetectEpic6RevenueRisk(pipelineId,request){return SCIIP_EPIC6_LEASING_REVENUE.detectRevenueRisk(pipelineId,request);}
function sciipCreateEpic6LeasingAction(request){return SCIIP_EPIC6_LEASING_REVENUE.createLeasingAction(request);}
function sciipActionEpic6LeasingAction(actionId,decision,options){return SCIIP_EPIC6_LEASING_REVENUE.approveAction(actionId,decision,options);}
function sciipExecuteEpic6LeasingAction(actionId,options){return SCIIP_EPIC6_LEASING_REVENUE.executeAction(actionId,options);}
function sciipTestV7Epic6ExecutiveLeasingTenantPipelineRevenueOperations(){var output=SCIIP_EPIC6_LEASING_REVENUE.certify();Logger.log(JSON.stringify(output));return output;}
