import{COPILOT_POLICY,confidenceBand}from'./copilotPolicy.js';
import{detectIntent,extractConstraints}from'./copilotIntent.js';
import{neighborsOf,queryGraph,graphSummary}from'../knowledge/graphQueryEngine.js';
const n=value=>{const parsed=Number(String(value??'').replace(/[$,% ,]/g,''));return Number.isFinite(parsed)?parsed:null};
const txt=value=>String(value??'').toLowerCase();
const attr=(node,...keys)=>{for(const key of keys){if(node.attributes?.[key]!==undefined&&node.attributes[key]!=='')return node.attributes[key]}return null};
function propertyMatches(node,c){const a=node.attributes||{};if(c.minSf&&Number(attr(node,'availableSf','buildingSf','sf','sizeSf')||0)<c.minSf)return false;if(c.minAmps&&Number(attr(node,'powerAmps','amps','power')||0)<c.minAmps)return false;if(c.minClearHeight&&Number(attr(node,'clearHeight','clearHt')||0)<c.minClearHeight)return false;if(c.status&&!txt(attr(node,'status','availability')).includes(c.status))return false;if(c.market&&!Object.values(a).some(v=>txt(v).includes(c.market))&&!txt(node.label).includes(c.market))return false;return true}
function evidenceItem(node,reason='Matched governed graph evidence'){return{id:node.id,type:node.type,label:node.label,reason,attributes:node.attributes||{}}}
function assignmentNodes(graph,assignmentId){const suffix=`:${String(assignmentId).toLowerCase().replace(/[^a-z0-9]+/g,'-')}`;const propertyIds=new Set((graph.edges||[]).filter(e=>e.type==='SUPPORTS_ASSIGNMENT'&&e.to.endsWith(suffix)).map(e=>e.from));return(graph.nodes||[]).filter(node=>node.type!=='Property'||propertyIds.has(node.id))}
function propertySearch(graph,question,assignmentId){const constraints=extractConstraints(question);const results=queryGraph(graph,{type:'Property',assignmentId}).filter(node=>propertyMatches(node,constraints));const score=results.length?Math.min(.96,.58+Math.min(results.length,8)*.045):.42;return{answer:results.length?`Found ${results.length} governed ${results.length===1?'property':'properties'} matching the requested criteria.`:'No governed properties currently match every requested criterion.',evidence:results.slice(0,COPILOT_POLICY.maxEvidenceItems).map(node=>evidenceItem(node)),confidence:score,constraints,recommendations:results.slice(0,5).map((node,index)=>({rank:index+1,nodeId:node.id,label:node.label,score:Math.max(60,95-index*6),explanation:'Matches the governed property criteria available in the active assignment graph.'}))}}
function assignmentSummary(graph,assignment){const nodes=assignmentNodes(graph,assignment.id);const properties=nodes.filter(n=>n.type==='Property');const markets=nodes.filter(n=>n.type==='Market');const sources=nodes.filter(n=>n.type==='Source');const summary=graphSummary({nodes,edges:graph.edges||[]});return{answer:`${assignment.name} is supported by ${properties.length} connected ${properties.length===1?'property':'properties'}, ${markets.length} ${markets.length===1?'market':'markets'}, and ${sources.length} governed evidence ${sources.length===1?'source':'sources'}. The assignment is currently in the ${assignment.stage} stage for ${assignment.location}.`,evidence:[...properties,...markets,...sources].slice(0,COPILOT_POLICY.maxEvidenceItems).map(node=>evidenceItem(node)),confidence:nodes.length?Math.min(.94,.6+nodes.length*.025):.38,metrics:summary}}
function comparableSupport(graph,assignment){const nodes=assignmentNodes(graph,assignment.id);const comps=nodes.filter(node=>/comp|comparable|transaction/i.test(`${node.type} ${node.label} ${JSON.stringify(node.attributes||{})}`));const properties=nodes.filter(node=>node.type==='Property');const evidence=comps.length?comps:properties;return{answer:evidence.length?`The assignment has ${evidence.length} governed ${evidence.length===1?'record':'records'} that can support comparable analysis. Review the evidence list before relying on a pricing conclusion.`:'No dedicated comparable evidence is currently connected to this assignment.',evidence:evidence.slice(0,COPILOT_POLICY.maxEvidenceItems).map(node=>evidenceItem(node,'Comparable-support evidence')),confidence:evidence.length?Math.min(.88,.52+evidence.length*.05):.34}}
function marketSummary(graph,assignment){const nodes=assignmentNodes(graph,assignment.id);const markets=nodes.filter(n=>n.type==='Market');const properties=nodes.filter(n=>n.type==='Property');return{answer:markets.length?`The active assignment is connected to ${markets.length} governed market ${markets.length===1?'entity':'entities'} and ${properties.length} property ${properties.length===1?'observation':'observations'}. This response reflects only evidence currently promoted into SCIIP_OS.`:'No governed market entity is connected to this assignment yet.',evidence:[...markets,...properties].slice(0,COPILOT_POLICY.maxEvidenceItems).map(node=>evidenceItem(node)),confidence:markets.length?.76:.36}}
function graphQuestion(graph,question,assignment){const terms=question.toLowerCase().split(/\W+/).filter(w=>w.length>3).slice(0,5);let hits=[];for(const term of terms)hits.push(...queryGraph(graph,{term,assignmentId:assignment.id}));hits=[...new Map(hits.map(n=>[n.id,n])).values()];return{answer:hits.length?`I found ${hits.length} connected graph ${hits.length===1?'entity':'entities'} relevant to the question. The evidence list shows the governed records used.`:'I could not find sufficient governed graph evidence to answer that question.',evidence:hits.slice(0,COPILOT_POLICY.maxEvidenceItems).map(node=>evidenceItem(node)),confidence:hits.length?Math.min(.84,.48+hits.length*.045):.25}}
export function askCopilot({graph,question,assignment}){const intent=detectIntent(question);let result;if(intent==='PROPERTY_SEARCH')result=propertySearch(graph,question,assignment.id);else if(intent==='ASSIGNMENT_SUMMARY')result=assignmentSummary(graph,assignment);else if(intent==='COMPARABLE_SUPPORT'||intent==='EXPLAIN_RANKING')result=comparableSupport(graph,assignment);else if(intent==='MARKET_SUMMARY')result=marketSummary(graph,assignment);else result=graphQuestion(graph,question,assignment);const confidence=Math.max(0,Math.min(1,result.confidence??0));return{requestId:`copilot-${Date.now().toString(36)}`,intent,question,answer:result.answer,evidence:result.evidence||[],recommendations:result.recommendations||[],constraints:result.constraints||{},metrics:result.metrics||{},confidence,confidenceBand:confidenceBand(confidence),grounded:(result.evidence||[]).length>0,approvalRequired:Boolean((result.recommendations||[]).length),policyVersion:COPILOT_POLICY.version,generatedAt:new Date().toISOString()}}
export function inspectEvidence(graph,nodeId){const node=(graph.nodes||[]).find(n=>n.id===nodeId);if(!node)return null;const neighborhood=neighborsOf(graph,nodeId);return{node,neighbors:neighborhood.nodes,relationships:neighborhood.edges}}
