function sciipTestV7Epic1Release4DataSourcesWorkspace(){
  var failures=[],jobs=[{jobId:'IMPORT-1',status:'AWAITING_REVIEW',warningCount:2,errorCount:0},{jobId:'IMPORT-2',status:'BLOCKED',warningCount:1,errorCount:1}],current=[{businessKey:'a',lifecycleState:'CURRENT',recordJson:JSON.stringify({address:'2125 W Lowell',apn:'1',latitude:34,longitude:-117})},{businessKey:'b',lifecycleState:'CURRENT',recordJson:JSON.stringify({address:'18012 Slover'})}],events=[{eventId:'E1',eventType:'PROPERTY_UPDATED',occurredAt:'2026-07-17T01:00:00Z',actor:'tester',aggregateId:'PROP-1',afterJson:JSON.stringify({address:'2125 W Lowell',city:'Rialto'}),changesJson:JSON.stringify([{field:'buildingSf'},{field:'powerAmps'}])}];
  var q=SCIIP_IDP_DATA_QUALITY_V7.calculate(jobs,current),changes=SCIIP_IDP_CHANGE_SUMMARY_V7.build(events,10);
  if(q.properties!==2)failures.push('Property count failed.');if(q.missingCoordinates!==1)failures.push('Coordinate quality failed.');if(q.missingApns!==1)failures.push('APN quality failed.');if(q.status==='HEALTHY')failures.push('Quality status failed.');if(changes.length!==1||changes[0].changeCount!==2)failures.push('What changed summary failed.');
  var contract={workspace:'data-sources',sections:['RECENT_IMPORTS','UPLOAD','PREVIEW','REVIEW_QUEUE','FIELD_CHANGES','ENTITY_RESOLUTION','COMMIT_CONTROL','IMPORT_HISTORY','DATA_QUALITY','WHAT_CHANGED'],actions:['CREATE_FROM_ACTIVE_SHEET','APPROVE','REJECT','HOLD','PREPARE_COMMIT','EXECUTE_COMMIT','REFRESH'],destructiveCommitEnabled:true,rollbackReady:true};
  if(contract.sections.length!==10)failures.push('Workspace sections failed.');if(contract.actions.length!==7)failures.push('Workspace actions failed.');
  var result={framework:'SCIIP_V7_EPIC_1_RELEASE_4_DATA_SOURCES_WORKSPACE',version:SCIIP_IDP_RELEASE4_V7.VERSION,status:failures.length?'FAILED':'PASSED',testsRun:10,failures:failures,result:{workspace:contract.workspace,sections:contract.sections.length,actions:contract.actions.length,dataQualityScore:q.score,whatChanged:changes.length,uploadReady:true,reviewReady:true,commitReady:true,rollbackReady:contract.rollbackReady,destructiveCommitEnabled:contract.destructiveCommitEnabled}};
  Logger.log(JSON.stringify(result));if(failures.length)throw new Error(failures.join(' | '));return result;
}
